### ISSUE TITLE
Settings breadcrumb incorrect for identity providers

### ISSUE THREAD

**Issue by mfrances17** [keycloak/keycloak-admin-ui#1016]
When you are adding a new SAML (or OIDC) provider, the breadcrumb is "Identity providers > Add SAML provider", which is expected. However, when you edit an existing provider, the same breadcrumb is displayed. It should change to something like "Identity providers > Settings".

**Comment by edewit** [comment]
@mfrances17 this has been fixed right?

**Comment by ssilvert** [comment]
@mfrances17 Can we close this?

**Comment by ssilvert** [comment]
@mfrances17 ^^^^
