### ISSUE TITLE
ID Provider fileUpload function should be added to Admin Client or as a separate util

### ISSUE THREAD

**Issue by mfrances17** [keycloak/keycloak-admin-ui#1024]
The OIDC and SAML providers both use a fileUpload function and duplicate the code within each other. The function should be added as a separate util to be shared by multiple different components, or it may make sense for the functionality to live in the Admin Client, as we suggested in this PR: 
https://github.com/keycloak/keycloak-admin-ui/pull/944#discussion_r690282726

**Comment by edewit** [comment]
fixed with #1415
