### ISSUE TITLE
Create user federation provider is broken

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-admin-ui#1042]
When you create the provider it says it was successful, but nothing got saved.

**Comment by mfrances17** [comment]
I can't reproduce this behavior, i'm able to create LDAP and Kerberos providers in the new admin console and they are persisted. I'm also able to view the ones I create (in the new console) in the old console.

**Comment by mfrances17** [comment]
Ok, never mind. I can reproduce it. Right now you can only create user fed providers on master, it's not working if you are on another realm other than master. Definitely an issue.
