### ISSUE TITLE
[UX Review] Some fine-tuning of Client scope detail page

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-admin-ui#1050]
Hi @edewit , there are some fin-tuning of client scope details page, please check and fix them.

1. The breadcrumb should be “Client scope > /Client scope name/ ”, like the screenshot shows below.
<img width="346" alt="Screen Shot 2021-08-24 at 3 32 00 PM" src="https://user-images.githubusercontent.com/53931519/130578245-c6354f6b-9b52-4e1c-8c63-a9c003d9eb61.png">

2. In the empty state, the toolbar can be removed.
<img width="927" alt="Screen Shot 2021-08-24 at 3 32 44 PM" src="https://user-images.githubusercontent.com/53931519/130578349-aba4b239-6cec-47c4-a050-2589652e8db4.png">

Thanks.

**Comment by edewit** [comment]
@xianli123 do we really want to have the name of the client scope there twice? Once as a title and once in the breadcrumb?

**Comment by xianli123** [comment]
@edewit I‘ve checked other pages and found the breadcrumb is "xx details". So we can keep the client scopes part as the same as the others. Does it make sense?
