### ISSUE TITLE
[UX Review] Unify the counting components across the console

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-admin-ui#1070]
In the new UI, I found the counting fields have 2 types of components as shown in the screenshot below. We can unify them and just keep one of them. And I think the second one is better.

> <img width="531" alt="Screen Shot 2021-08-26 at 11 13 22 AM" src="https://user-images.githubusercontent.com/53931519/130895703-fad1fb8c-de81-406d-b313-1d5a55d651ab.png">

**Comment by edewit** [comment]
we can't use the recommend one as we want to be able to use a blank as a valid value

**Comment by xianli123** [comment]
Yes, I forgot to close this issue. Thanks.
