### ISSUE TITLE
Identity providers: Unrecognized field "samlEntityDescriptor"

### ISSUE THREAD

**Issue by jenny-s51** [keycloak/keycloak-admin-ui#1080]
Steps to repro:

1. Go to Identity Providers 
2. Click "Add provider"
3. Select "SAML v2.0"
4. "Use entity descriptor" is toggled on
5. Populate all the required fields and save
6. The `name="samlEntityDescriptor"` on the last field triggers a 400 error because `samlEntityDescriptor` is not an attribute of `IdentityProviderRepresentation`.

**Comment by ssilvert** [comment]
@mfrances17 Can you take a look at this soon after you are back?  It's something anyone creating a SAML provider will likely run into.

**Comment by edewit** [comment]
fixed in #1415
