### ISSUE TITLE
[UX Review] Mapper configurations - Role name mapper

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-admin-ui#1100]
Hi @edewit , there are some fine-tuning of adding "Role name mapper". Please check them.

> <img width="848" alt="Screen Shot 2021-08-31 at 11 39 24 AM" src="https://user-images.githubusercontent.com/53931519/131439917-46c62af0-1399-494c-ac83-1d8e8dc640bc.png">

1. The "Mapper type" should display the selected type and it's read-only.
2. In the Roles filter, the dropdown list should list out all the clients that can be selected.

> <img width="752" alt="Screen Shot 2021-08-31 at 11 41 14 AM" src="https://user-images.githubusercontent.com/53931519/131440216-7c0f36e7-472a-4384-930d-9a6e8d4b011b.png">
3. We can display 5 options and add a scrollbar to allow users view all options.

**Comment by edewit** [comment]
> 2. In the Roles filter, the dropdown list should list out all the clients that can be selected.
What do you mean with: "can be selected"? Right now it filters out the clients that don't have roles

**Comment by xianli123** [comment]
I am sorry. I missed this filtering mechanism. It is good to filters out the clients that don't have roles. Thanks.

Another question: When I first clicked the drop-down, there was no client listed as shown below. Is this a bug? Or is there a problem with my server?
> <img width="726" alt="Screen Shot 2021-08-31 at 3 46 52 PM" src="https://user-images.githubusercontent.com/53931519/131464504-2b4cec57-c4fd-4bce-8837-368293dee2f6.png">

**Comment by edewit** [comment]
That is a bug...

**Comment by xianli123** [comment]
I see. Please fix it. thx
