### ISSUE TITLE
[UX Review] The Test button shouldn't report success when the Bind DN/credential is wrong

### ISSUE THREAD

**Issue by yih-wang** [keycloak/keycloak-admin-ui#1114]
Location: User federation -> Create provider

When the Bind type is Simple, and the bind credential isn't been input. The system should report failure instead of success when the user presses the Test button. 

![image](https://user-images.githubusercontent.com/23331885/131820945-9cfe071b-26df-46fb-af59-0fde6f5678f9.png)

Also, when the user inputs a wrong Bind DN, the Test button reports success.

**Comment by jonkoops** [comment]
I don't know if we actually have control over this message is the result of an API call ([see the code](https://github.com/keycloak/keycloak-admin-ui/blob/master/src/user-federation/ldap/LdapSettingsConnection.tsx#L55-L71)).

@yih-wang Can you share with me the form values you are using to reproduce this issue?

**Comment by yih-wang** [comment]
> I don't know if we actually have control over this message is the result of an API call (see the code).

@jonkoops Yes, I think so. The alert works well in the old console.

So the issue is, we used to have two different buttons to test connection & authentication separately in the old console (see the screenshot below). 
![image](https://user-images.githubusercontent.com/23331885/132342887-2c62d7e6-f426-456f-9a6b-89e96927fe25.png)
In the new design, there is only one button left to test all the things. However, in the current implementation, this button only validates the connection, but not the authentication.

To reproduce that, you can type "ldaps://ldap.jumpcloud.com:636" as the Connection URL (to avoid a connection error), and then directly click Test at the bottom of this section. You'll find it successful without validating the Bind DN or credential.

Having said that, I'm kind of thinking that we should still provide two separate buttons in the new console instead of one. During user testing, we found that LDAP is complicated for most of the users so that more validations can give them more confidence. @ssilvert Do you have an opinion on that? Do you think it makes more sense to validate connection and authentication separately, like the screen below?
![image](https://user-images.githubusercontent.com/23331885/132345401-a9be2d6a-dd50-481c-8ea4-985b136b2d34.png)
