### ISSUE TITLE
Key providers not sorted

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-admin-ui#1159]
1. Create a new Realm
2. Go to Realm settings --> Keys --> Providers
3. Drag `rsa-enc-generated` to the top
4. It will immediately be placed back at the bottom of the list

It appears that the list is not sorted, so it is just displaying the keys in the order they were returned by the server.  Therefore, it appears that the drag and drop did not work.  If you go to the old console, you can see that it looks like the priorities of all the key providers was properly changed.  So I am assuming that the problem is that the list is just left unsorted.  This list should be sorted by priority with the highest priority at the top.

**Comment by ssilvert** [comment]
Actually, I think I'm wrong about the cause of the problem.  If you add a provider, it does not show up in the list unless you go out of `Realm settings` and go back in.  Then when you go back in the list is properly sorted.

So it looks like the issue is that the table simply is not updated when you drag and drop or when you add a provider.

**Comment by edewit** [comment]
This is fixed now right?
