### ISSUE TITLE
Custom fields for mapper types need cleanup

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-admin-ui#1216]
1. Go to Client scopes --> Mappers --> Add mapper --> By configuration
2. Select a mapper type such as "Javascript Mapper"
3. This mapper has one custom field called "Script".
4. The help text for this custom field is incorrect.

There are similar issues on other of these custom fields.  For some the help text is wrong,  For others, the field name is not found in the message bundle (example is `name-id-format` for `User Attribute Mapper For NameID` mapper type.

Someone needs to go through all these and make sure the help text and attribute names match the old console.

**Comment by edewit** [comment]
Seem to me the help text of the Javascript Mapper is correct, old console:
![image](https://user-images.githubusercontent.com/51133/134636216-d6db3a03-8dd5-429d-a843-223981396bf9.png)
New console:
![image](https://user-images.githubusercontent.com/51133/134636313-c200105d-9d5c-41bb-a18c-a7a5a50add05.png)

**Comment by edewit** [comment]
oh wait I see it's only part of the text... and let's format the newlines as well

**Comment by edewit** [comment]
there is also a missing label on keycloak itself [KEYCLOAK-19329](https://issues.redhat.com/browse/KEYCLOAK-19329)
