### ISSUE TITLE
Flicker on left nav

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-admin-ui#123]
The left navigation menu flickers whenever you select something.

**Comment by ssilvert** [comment]
Partially fixed by https://github.com/keycloak/keycloak-admin-ui/pull/214 .

Still need to fix this for realm selector.

**Comment by edewit** [comment]
@ssilvert it's not a flicker there is a loading indicator, when the loading is done the realm selector is there. It happens so fast that you might notice it as a flicker. So question is how do you want to solve this? Remove the loading indicator or make the loading indicator a dropdown with no realms?

**Comment by ssilvert** [comment]
@edewit Ideally, I'd like us to solve it in much the same way you solved #214 .  There should be no reason to refresh that part of the page when all you are doing is moving from one section to the other.

Also, the only time you even get a dropdown is when you are logged into Master.  If you are logged into a single realm you are only managing that one realm and you aren't allowed to create new realms.  I don't think we account for that yet.

So the whole thing will require a little more thought.

**Comment by edewit** [comment]
Yes when you only manage a single realm, right now we show a dropdown with only one item in it. We could not render anything when you only have one realm and no rights to create a second.

**Comment by edewit** [comment]
This was fixed as some point
