### ISSUE TITLE
Can't set SAML Principal type to Transient

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-admin-ui#1250]
1. Go to Identity providers -- > some SAML provider --> Provider details
2. Set `NameID policy format` to `Transient`
3. Set `Principla type` to `Subject NameID`
4. Hit `Save`
5. You will get the message `Could not update the provider Can not have Transient NameID Policy Format together with SUBJECT Principal Type`
6. This is correct
7. Now change `principal type` to ` Attribute [Name]`
8. Fill in something for `Principla attribute`
9. Hit save and you will get the same message, which is incorrect.  It should allow you to save.

**Comment by mfrances17** [comment]
This was fixed as part of https://github.com/keycloak/keycloak-admin-ui/pull/1377. Closing.
