### ISSUE TITLE
Realm roles: Can't add client roles as associated roles

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-admin-ui#1288]
In Realm roles, it only allows you to add other realm roles as an associated role.  You should also be able to add client roles.

**Comment by jenny-s51** [comment]
@ssilvert I've tested this in both Keycloak 15 and 16 and I am unable to reproduce this. Would you mind confirming whether or not you are still seeing this? If I add a client role as the first role, I get the `Associated Roles` tab and the client role shows up when I reload as well.

**Comment by ssilvert** [comment]
@jenny-s51 @jonkoops I have verified that this is now working.  Closing it.
