### ISSUE TITLE
Create a provider for alerts

### ISSUE THREAD

**Issue by edewit** [keycloak/keycloak-admin-ui#132]
Right now any page that wants to display an alert needs to add a component. Make it that it's only added once and that there is a provider to access it.

**Comment by edewit** [comment]
@ssilvert would that really be a enhancement though? Instead of:

```html
<Alert />
```
this:

```html
<AlertConsumer>
    {({ addAlert }) => (
         <Button onClick={() => addAlert("the alert")}>Test</Button>
    )}
</AlertConsumer>
```
Or did you have something else in mind?

**Comment by ssilvert** [comment]
What I have in mind is an `addAlert` function that is passed to a component, either through a context or a property.  That's all I should need to add an alert.  There would only be one instance of `<Alert />` in the whole system.

Right now I think we have more pressing issues though.
