### ISSUE TITLE
Search box behavior

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-admin-ui#1348]
This can be addressed Post 1.0

In our search boxes, the `x` button should dismiss the search and restore all rows to the list.  However, it requires that you press `Enter` on the empty search box to actually remove the search.

**Comment by edewit** [comment]
This is not possible with the current PF component we are using, we could switch to use the `SearchInput` they recently introduced that will change how it looks a bit though, old design:
![image](https://user-images.githubusercontent.com/51133/159226988-d590fdae-3d12-41c6-a049-5d1bf1133925.png)

new:

![image](https://user-images.githubusercontent.com/51133/159226904-80a3442a-869e-4d99-8da0-f25531b8e59c.png)
