### ISSUE TITLE
OIDC mapper: Attribute Importer's attribute name not saved

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-admin-ui#1350]
1. Go to Identity providers --> OIDC provider --> Edit Identity Provider Mapper
2. Select Mapper type `Attribute Importer`
3. Fill in all fields and save.
4. Go back to mapper list
5. Select the mapper you just created.
6. `User Attribute Name` will be blank

**Comment by mfrances17** [comment]
This is unreproducible in the latest build. I've done the exact steps above and I've verified that the User Attribute Name is properly saved in the new admin console, and verified that the write occurred by viewing it in the old admin console as well. 

@ssilvert please retest and close this issue if your results are the same as mine

**Comment by ssilvert** [comment]
Yep.  Looks like it got fixed.
