### ISSUE TITLE
`Query supported extensions` missing from LDAP provider

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-admin-ui#1390]
User Federation --> LDAP settings --> Advanced section

The old console has a button for `Query supported extensions`.  I don't see this in the new console.

**Comment by edewit** [comment]
Am I reading this right all that that does is set `usePasswordModifyExtendedOp` a.k.a "Enable the LDAPv3 Password Modify Extended Operation" based upon that query

**Comment by edewit** [comment]
@xianli123 is this something we need, or is this feature removed?

**Comment by ssilvert** [comment]
I asked the wider Keycloak team about this on the mailing list.

**Comment by stianst** [comment]
This was added as part of https://github.com/keycloak/keycloak/pull/6962 / https://issues.redhat.com/browse/KEYCLOAK-10927

It seems it was discussed through the PR and agreed to keep it, so we should include in the new admin console as well. @mposolda can confirm this though.

**Comment by edewit** [comment]
working on it now

**Comment by edewit** [comment]
@stianst it seems that this call only sets one "Enable the LDAPv3 Password Modify Extended Operation" flag to either true or false is that really all that is needed?

**Comment by stianst** [comment]
> @stianst it seems that this call only sets one "Enable the LDAPv3 Password Modify Extended Operation" flag to either true or false is that really all that is needed?

I'd think so, but worth double checking with @mposolda since we're not 100%

**Comment by mposolda** [comment]
@edewit Yes, right. Right now, it sets only "Enable the LDAPv3 Password Modify Extended Operation" flag to either true or false. The intent was to use "Query Supported Extensions" eventually for more things in the future, but right now it is just this single flag.

**Comment by edewit** [comment]
super, that's what I've reimplmented now as well
