### ISSUE TITLE
[UX Review] Fix UX issues of the Attributes tabs

### ISSUE THREAD

**Issue by yih-wang** [keycloak/keycloak-admin-ui#1418]
Motivation:
There're some UX issues found in the current solution of the Attributes tabs, the related discussion can be found in #1383 

Scope:
All the Attributes tabs around the console
- Users
- Groups
- Realm roles

New design:
https://marvelapp.com/prototype/6a22eh8

**Comment by edewit** [comment]
can this be closed?

**Comment by xianli123** [comment]
Yes, I think we can close it. What do you think? @jonkoops

**Comment by jonkoops** [comment]
Yeah, I think this can be closed.
