### ISSUE TITLE
Cannot assign multiple resources to a single permission

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-admin-ui#1463]
This is opened to make sure that the design for authorization allows expected behavior detailed in [KEYCLOAK-19683.](https://issues.redhat.com/browse/KEYCLOAK-19683)

**Comment by edewit** [comment]
it's designed that way: https://marvelapp.com/prototype/6a7eeb2/screen/83188301

**Comment by ssilvert** [comment]
@edewit Can this be closed?  If so, please go ahead and close it.
