### ISSUE TITLE
User Fed: role-ldap-mapper has wrong defaults

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-admin-ui#1481]
1. Go to User Federation --> LDAP --> LDAP Mappers
2. Create new mapper
3. Choose `role-ldap-mapper` as mapper type

`Role Object Classes` has wrong default.  Should be `groupOfNames` instead of `group`
`User roles retrieve strategy` has three choices.  It should have only two.  See old console.

**Comment by mfrances17** [comment]
The `Role Object Classes` issue will be fixed as part of https://github.com/keycloak/keycloak-admin-ui/pull/1511.

After testing and reproducing this issue, it seems that `User roles retrieve strategy` is another case of the Active Directory vendor having different values that the other 4 vendor types. In this case, there are 3 available choices for AD and just 2 for the other vendors.

Will have a fix soon, just wanted to add context to the issue.
