### ISSUE TITLE
[UX Review] Updates of SAML client creation

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-admin-ui#1513]
Hi @edewit, In the new design, the **Encrypt assertions** and **Client signature required** have been moved to the Keys tab, And they are not considered as the capability configs. Therefore if users want to create a SAML client, they don't need to set up the capability configs. We can remove the capability configs in the creation page when users selected the SAML protocol. Thanks.

<img width="747" alt="Screen Shot 2021-11-09 at 3 00 59 PM" src="https://user-images.githubusercontent.com/53931519/140877328-f7673cdd-b1f5-4bcc-8940-69168b47dc9e.png">

**Comment by edewit** [comment]
so in case of a saml client you have a wizard with only one step?

**Comment by xianli123** [comment]
hi @edewit  We can put this issue aside for now. Because the OIDC client creation also has some updates. We need to rethink the creation pages. Once I have some updates, we can discuss them again. WDYT?

**Comment by xianli123** [comment]
hi @edewit Haley and I discussed this part. In the new design, "Encrypt assertions" and "Client signature required" are not the capability configs anymore. So we can remove this step from the SAML creation process. Thanks.
