### ISSUE TITLE
SAML import config causes server side error

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-admin-ui#1535]
### Describe the bug

SAML import config causes server side error

### Version

16.0.0

### How to Reproduce?

Create a new SAML identity provider and provide the SAML config file attached.  You will get the following error on the server:
`ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-19) Uncaught server error: java.lang.RuntimeException: com.ctc.wstx.exc.WstxEOFException: Unexpected EOF in prolog
 at [row,col {unknown-source}]: [1,0]`

This does not happen on the old UI.  In looking at the difference in requests, I view the source for the form data.  I suspect that the problem is the content type.  The new UI has `Content-Type: application/octet-stream`.  The old UI has `Content-Type: text/xml`.

Unzip the descriptor below.   It is taken from [wikipedia](https://en.wikipedia.org/wiki/SAML_metadata), but has the KeyDescriptor section removed.
[saml-descriptor.zip](https://github.com/keycloak/keycloak-admin-ui/files/7517096/saml-descriptor.zip)

**Comment by edewit** [comment]
That was not the reason, it didn't work because it was triggered twice once a working request and another with an empty string.
