### ISSUE TITLE
Creating a new realm role is not possible

### ISSUE THREAD

**Issue by agagancarczyk** [keycloak/keycloak-admin-ui#1539]
### Describe the bug

The new role form is not displaying on clicking the "Create role" button

### Version

15.0.2

### Expected behavior

A new role form should display.

### Actual behavior

The spinner is showing all the time.

### How to Reproduce?

Go to Realm roles sidebar menu item and click "Create role". Observe the issue.

**Comment by iethem** [comment]
Also, the role name field is empty when editing.

**Comment by agagancarczyk** [comment]
> Also, the role name field is empty when editing.

yes, that's correct, I'll take a look at it as well, thank you @iethem

**Comment by edewit** [comment]
fixed with https://github.com/keycloak/keycloak-admin-ui/pull/1497/commits/5a55b711d45c25c8cf26a57d74cc360246e3a400
