### ISSUE TITLE
[UX Review] SAML client settings updates

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-admin-ui#1563]
### Describe the bug

Hi @edewit , I found there are some differences between the new UI and the current console. Could you please check the design below and update the current implementation? Here is the design link: https://marvelapp.com/prototype/880h4f8/screen/82212914 Thanks.

### Version

New admin UI

**Comment by ssilvert** [comment]
@xianli123 Please be more specific about what is wrong here.  I don't know how to set the impact so I made it medium for now.

**Comment by xianli123** [comment]
> 

There are lots of details that should be fixed. I can create some small issues to specify what should be fixed. Does it make sense?

**Comment by xianli123** [comment]
hi @ssilvert  I created some new issues about SAML client settings. I think we can close this issue. What do you think?

**Comment by ssilvert** [comment]
@xianli123 OK.  Closing this one as it is handled in the new issues.

**Comment by xianli123** [comment]
OK. Thanks.
