### ISSUE TITLE
[UX review] Add two new parts in Client scopes evaluate page

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-admin-ui#1564]
### Describe the bug

Hi @edewit , Compared to the old console, there are 2 new parts in the **_Client scopes evaluate_** page named "**Generated ID Token**" and "**Generated User Info**". 

They are both code blocks. We can use the PF4's component named "code block". Here is the component link: https://www.patternfly.org/v4/components/code-block#basic. But I am not sure if we can remove the icons and just leave the code area. Could you please add these 2 new parts and check the PF4's component? Thanks.

### Version

New admin UI

**Comment by ssilvert** [comment]
@xianli123 Is this a new feature that is not present in the old UI?  
Maybe it needs to be marked as kind/enhancement instead of kind/bug?
Also, where is the design for this?

**Comment by xianli123** [comment]
> @xianli123 Is this a new feature that is not present in the old UI? Maybe it needs to be marked as kind/enhancement instead of kind/bug? Also, where is the design for this?

@ssilvert This is a new feature in the latest version.
I will change the type from "kind/bug" to "kind/enhancement".
As for design, these 2 parts are code blocks, so we can use the PF4 component directly and I can offer the layout of these 2 parts later.

**Comment by edewit** [comment]
@xianli123 yes it's possible to remove the buttons.

**Comment by xianli123** [comment]
We need to add 2 parts in the Evaluate page named **Generated ID Token** and **Generated User Info**. There are the layouts of them as shown in the screenshot below. Both of them can be implemented by the code-block component. Here is the component link. https://www.patternfly.org/v4/components/code-block#basic

<img width="935" alt="Screen Shot 2022-02-08 at 2 50 34 PM" src="https://user-images.githubusercontent.com/53931519/152934395-1b5dbc7b-8568-4f41-9ab7-3dfba1d99f4b.png">
 
<img width="936" alt="Screen Shot 2022-02-08 at 2 51 34 PM" src="https://user-images.githubusercontent.com/53931519/152934417-d75a15df-fe6e-418f-a4c8-ba24545591fc.png">
