### ISSUE TITLE
[UX Review] Mappers details

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-admin-ui#1629]
### Describe the bug

Hi @edewit , there are some fine-tuning of the mapper details page in the "Client scopes". Please check them. Thanks.
<img width="1143" alt="Screen Shot 2021-12-01 at 11 14 41 AM" src="https://user-images.githubusercontent.com/53931519/144166131-ea5469a3-e4f7-41e6-8354-1d47a9582e73.png">

1. We can add the "ID" as the tag, as the picture shows below.
<img width="654" alt="Screen Shot 2021-12-01 at 11 23 18 AM" src="https://user-images.githubusercontent.com/53931519/144166535-4b741ab0-91f6-47d1-9fa1-8529a8985b5e.png">

2. These three labels are confusing. We can use the label of the current console.

### Version

New admin UI

**Comment by ssilvert** [comment]
@xianli123 I think this is fixed.  Can you please verify and close it if this is fixed?

**Comment by xianli123** [comment]
@ssilvert I've reviewed this part. I found the first bug, namely, adding the **ID** tag, wasn't fixed.  Could you please check the first bug? BTW, the second bug has been fixed.

**Comment by ssilvert** [comment]
@xianli123 Looks fixed to me.  I see the ID tag.  Do you not see it?

**Comment by xianli123** [comment]
@ssilvert Sorry for the late reply. This issue is fixed. So I think we can close this issue. What do you think?
