### ISSUE TITLE
[UX Review] Update the search results page of Event

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-admin-ui#1630]
### Describe the bug

hi @agagancarczyk , I have reviewed the Events UI and found an issue on the search results page if there is no result as shown in the screenshot below.

> <img width="1139" alt="Screen Shot 2021-12-01 at 3 38 05 PM" src="https://user-images.githubusercontent.com/53931519/144191679-23dbc0e8-2106-4630-8df3-77255d5a3fff.png">

In order to better optimize this page, I created a new screen as shown below. If there is no search result, it will be displayed as an empty state, and clicking the "Clear all filters" button will return to the original page. What do you think? Thanks.

<img width="640" alt="Screen Shot 2021-12-01 at 3 31 28 PM" src="https://user-images.githubusercontent.com/53931519/144191413-7959ab5e-f326-4295-b438-104b3be62a19.png">
 

### Version

Admin new UI

**Comment by edewit** [comment]
@xianli123 this has been fixed already I think we can close this one

**Comment by xianli123** [comment]
@edewit Yes. I've reviewed the new UI. It looks good to me.
