### ISSUE TITLE
[UX Review] Change the fields' order in the User Address mapper

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-admin-ui#1659]
### Describe the bug

In the new UI, I found the order of the fields is different from the current console. We can change the order to align with the current console. In addition, these three labels are confusing. We can refer to the current console to correct them.

**New UI**
<img width="1073" alt="Screen Shot 2021-12-06 at 2 40 46 PM" src="https://user-images.githubusercontent.com/53931519/144800141-5f1061f5-6d3a-4406-b4c6-a7e67bd95338.png">

**Proposal**
<img width="654" alt="Screen Shot 2021-12-06 at 2 49 12 PM" src="https://user-images.githubusercontent.com/53931519/144800578-112a3bd7-4c8e-49bf-8503-ff5b7ec6a5a4.png">

### Version

New Admin UI

**Comment by edewit** [comment]
I don't see a difference in rendering though, old console:
![image](https://user-images.githubusercontent.com/51133/146357195-99e3f3ce-d54a-435d-8037-f141e60d4324.png)
new console:
![image](https://user-images.githubusercontent.com/51133/146357316-4a52d5e9-2554-44a3-8018-056964b96b62.png)
These screens are dynamic so changing them would require backend changes

**Comment by edewit** [comment]
closing as the a possible change in this behaviour would mean a server side change
