### ISSUE TITLE
[UX Review] Optimize the button wording of the revoke modal in User consents

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-admin-ui#1703]
### Describe the bug

In the User-Consents page, there will be a modal popup after clicking the **Revoke** option inside the kebab menu. In this modal, the primary button is "Delete". We can change the button from "Delete" to "Revoke" as shown in the screenshot below. Thanks.
<img width="855" alt="Screen Shot 2021-12-14 at 2 01 11 PM" src="https://user-images.githubusercontent.com/53931519/145943962-223ee1b9-07f8-4a60-a062-51c3431b6298.png">

### Version

New admin UI

**Comment by dominikkawka** [comment]
Hey @xianli123 , I tried taking a look just now but for my consent page I get this 
![image](https://user-images.githubusercontent.com/31955648/178988978-fa75db1d-3368-4883-b3da-aed0c2def247.png)

What are the steps required for me to get this issue? Thanks

**Comment by xianli123** [comment]
Hi @dominikkawka If you want to see the consents of the user. You need to configure the client named "security-admin-console-v2".

1. You can enable the "Consent required" and "Display client on screen" in the settings page of the "security-admin-console-v2" client. 
2. Then you can logout and login again. 
3. You will find some consents in the User>Consent page. 
4. After clicking the kebab menu, there will be an option list that includes "Revoke" option.
5. After clicking the "Revoke", you will the modal as I showed originally.

<img width="785" alt="Screen Shot 2022-07-15 at 10 11 47" src="https://user-images.githubusercontent.com/53931519/179133175-57467657-a34a-492c-8843-a30db189b16b.png">

If it doesn't work, please feel free to let me.
