### ISSUE TITLE
Some of the social IdP icons are missing

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-admin-ui#1720]
### Describe the bug

Some of the social IdP icons are missing
![image](https://user-images.githubusercontent.com/507202/146440113-9d96c238-5368-44bb-9d7d-e545bd8224ca.png)

### Version

15.1.0

### Anything else?

Source is [keycloak/keycloak#9119 (comment)](https://github.com/keycloak/keycloak/discussions/9119#discussioncomment-1823140)

**Comment by ssilvert** [comment]
Technically, this should be low impact.  But because it looks so bad, we need to fix it sooner.

**Comment by edewit** [comment]
One thing that just popped into my mind is that in the past we had issues with using company logo's due to copy right laws, are we sure that in these cases that that is fine?

**Comment by ssilvert** [comment]
@edewit If it's in PatternFly then I'm assuming they have done the due diligence to make sure it's OK.  @mfrances17, do you know for sure?

**Comment by edewit** [comment]
it has nothing to do with patternfly. my concern is about copy right law on these company logos.

**Comment by ssilvert** [comment]
@edewit I understand.  But these logos come to us from PatternFly and I'm assuming that the PatternFly team has done due diligence to make sure they are legal for everyone to use.

@mfrances17 Do you know anything about this?

**Comment by ssilvert** [comment]
@edewit BTW, it looks like this is fixed.  Can we close it?

**Comment by edewit** [comment]
it will be fixed when the PR is merged it currently only works when doing a `npm start` not when running off of keycloak
