### ISSUE TITLE
[UX Review] Searching user will return an error "No users found due to" when there're unavailable federated providers

### ISSUE THREAD

**Issue by yih-wang** [keycloak/keycloak-admin-ui#1751]
### Description

When there're federated providers set up in the realm and at least one of them doesn't work, searching user in the Users section will get the following error message:
![image](https://user-images.githubusercontent.com/23331885/147063656-b204df52-5366-4e10-853b-6667b839dce0.png)

It's not obvious that the issue is led by the federated provider settings. Should improve the message to clarify that, or at least ask users to check the log.

**Comment by edewit** [comment]
The same thing happens in the old console, but there you still have to option to click the "view all users" option, do we want to add that again?

**Comment by yih-wang** [comment]
@edewit I'm not sure whether it's a good idea to add the "view all users" option to this case, or I don't know how to define the case. Suppose the user has set up 3 providers, 1 of them doesn't work. We won't want the user to "view all users" in this scenario as that may cause the system to slow down when the working providers have tons of users. But also the user cannot search anything as there's also a down provider. 

I prefer to improve the error message to clarify there's a provider that doesn't work. The user should fix that (or at least disable that single provider) before searching any user. Is it possible to do that?

@xianli123 Can you follow up on this issue? Thanks!

**Comment by xianli123** [comment]
@yih-wang My pleasure. I will take over this issue.

**Comment by edewit** [comment]
If we want a better error message it will be a server side change though

**Comment by xianli123** [comment]
@edewit  I think that if the user wants to view the user and the search function doesn't work, there should be a way to view the user. There should also be a prompt to let the user know that some providers or federations are not working.

**Comment by xianli123** [comment]
> If we want a better error message it will be a server side change though

Is it possible to change the error message for now?

**Comment by edewit** [comment]
we could guess that there could be something wrong with the federations and show a hint, how about that?
