### ISSUE TITLE
[UX Review] The search function of Realm roles doesn't work

### ISSUE THREAD

**Issue by yih-wang** [keycloak/keycloak-admin-ui#1757]
### Describe the bug

The search in the associated roles tab doesn't work. The results that don't match the keywords will still show up.

![image](https://user-images.githubusercontent.com/23331885/147197624-19aea93e-4b64-459a-a812-d131ff303814.png)

### Version

15.0.2

**Comment by mfrances17** [comment]
As of 2/10/22, I can't reproduce this issue with the latest code in main. @yih-wang can you verify with the latest build? Here are my results from testing:

![zd-search](https://user-images.githubusercontent.com/39063664/153525221-71bdcfbe-8c19-4f1a-9755-b6e74189b607.png)

![client-search](https://user-images.githubusercontent.com/39063664/153525227-5789857e-45ed-41a5-a93c-53b36cb7f84f.png)
