### ISSUE TITLE
[UX Review] Users > role mappings: the inherited relationship doesn't show correctly

### ISSUE THREAD

**Issue by yih-wang** [keycloak/keycloak-admin-ui#1758]
### Describe the bug

In the following screenshot, there're four roles are inherited from "default-roles-pwless" and one inherited from "manage-account". But the "Inherited from" column is all empty.

![image](https://user-images.githubusercontent.com/23331885/147197863-6540b480-ee14-4a95-979d-402682fc8fb7.png)

### Version

15.0.2

**Comment by edewit** [comment]
where do you see the `Inherited from` again in the old console?

**Comment by yih-wang** [comment]
@edewit Not sure whether I got the question correctly. There isn't a place that can directly check which role the effective roles are inherited from in the old console. The only way to know that is to check the associated roles of the assigned roles. For example, in the screenshot below, there're 3 roles that are effective but are not directly assigned. 

![image](https://user-images.githubusercontent.com/23331885/156980696-717d28b0-51fa-42c3-a01b-60f432eb9aae.png)

After checking the composite part of Admin and Default-roles-master, we can know that the "create-realm" is associated with "admin". "Offline-access" and "uma_authorization" are associated with "default-roles-master". So the "create-realm" should be inherited from "admin". "Offline-access" and "uma_authorization" should be inherited from the "default-roles-master".

![image](https://user-images.githubusercontent.com/23331885/156982152-8becb585-ee52-4bb6-9085-cef9c70a3487.png)

**Comment by edewit** [comment]
I remember now why that is, it's because the backend doesn't support this and after talking to the backend team they said it's unfeasible to have this data at this level

**Comment by ssilvert** [comment]
@edewit Let's just change the column name to "Inherited?".  Then if it is inherited, put a check mark or something in the column.  Otherwise, leave it blank (no dashes).

WDYT?

**Comment by edewit** [comment]
Okay

**Comment by ssilvert** [comment]
> Okay, but that is already indicated by the row being disabled

@edewit Yes, but the user won't know that "disabled checkbox" means "inherited role".  If the user selects "Hide inherited roles" he might figure it out.  But I think we still need something that makes this more clear.
