### ISSUE TITLE
[UX Review] Users > role mappings > assign role modal: the modal is empty when no results match the filter

### ISSUE THREAD

**Issue by yih-wang** [keycloak/keycloak-admin-ui#1761]
### Describe the bug

When there're no realm roles in the realm and use _realm role_ as a filter, the toolbar and content will both disappear.
![image](https://user-images.githubusercontent.com/23331885/147198988-aaefe2f0-5142-4c50-a90e-9e8b8102a3cb.png)

![image](https://user-images.githubusercontent.com/23331885/147199009-6e8f5e48-bdea-4ba3-9ea0-353738d3578c.png)

### Version

15.0.2

### Expected behavior

Show an empty state like this:
![image](https://user-images.githubusercontent.com/23331885/147199173-650d1d6d-f4b1-4491-bedf-6c6b08eb36b9.png)

**Comment by ssilvert** [comment]
This state can no longer occur.  The built-in realm roles can not be deleted.  Closing.
