### ISSUE TITLE
[UX Review] Realm partial import: default to select all resources after importing a file

### ISSUE THREAD

**Issue by yih-wang** [keycloak/keycloak-admin-ui#1768]
### Description

Change the checkboxes to be default selected
![image](https://user-images.githubusercontent.com/23331885/147208300-7000c755-3de3-4742-92a2-67bd743498e2.png)

**Comment by ssilvert** [comment]
I'm going to close this as I believe the boxes should remain uncheked by default.  I think a user should take a positive action to do the import.  It can lead to errors if the user does not think about what he is importing as it has the potential to corrupt his data.

I know it is selected by default in the old UI, but as the one who originally designed and implemented this in the old UI, I'm going to take the prerogative and change my mind.
