### ISSUE TITLE
[UX Review] Realm partial import doesn't return any result

### ISSUE THREAD

**Issue by yih-wang** [keycloak/keycloak-admin-ui#1769]
### Describe the bug

The realm partial import doesn't return any result (error alert, success screen) after clicking _import_.

### Version

15.0.2

### Expected behavior

https://marvelapp.com/prototype/fg26f9b/screen/75624796

**Comment by ssilvert** [comment]
@yih-wang This is working for me.  Can you attach a reproducer?

**Comment by ssilvert** [comment]
@yih-wang Also, from the screen shot in the other issue, I can tell that you were using an old version of the code.  So please do an update and retest.

**Comment by yih-wang** [comment]
@ssilvert I update the code and it works. Close this issue.
