### ISSUE TITLE
[UX Review] Realm settings > tokens: SSO session idle should be a variable

### ISSUE THREAD

**Issue by yih-wang** [keycloak/keycloak-admin-ui#1778]
### Describe the bug

The value here should follow the real value of the SSO session idle in the Sessions tab
![image](https://user-images.githubusercontent.com/23331885/147222873-09fcfdad-7a3b-4a7b-a965-fdb843a615da.png)

### Version

15.0.2

**Comment by edewit** [comment]
It does though, can this be closed?

**Comment by yih-wang** [comment]
@edewit Ah ok, I found it does after I refreshed the browser. Is it possible to update the number in the Tokens tab after the number in the Sessions tab has been changed and saved (without refreshing the browser)?
