### ISSUE TITLE
SyntaxError: Invalid regular expression: invalid group specifier name on safari

### ISSUE THREAD

**Issue by jaynmfs** [keycloak/keycloak-admin-ui#1806]
### Describe the bug

The error "SyntaxError: Invalid regular expression: invalid group specifier name" occur when I access Keycloak console with new admin ui (v2) on safari.

### Version

16.1.0

**Comment by jonkoops** [comment]
I don't have access to a Mac so I cannot confirm this issue, @edewit @agagancarczyk could either of you confirm this?

**Comment by edewit** [comment]
I can confirm that this is happening just tested it on my old laptop, don't have a development environment on that though.

**Comment by jonkoops** [comment]
Thanks for confirming @edewit.

**Comment by jonkoops** [comment]
@jaynmfs @edewit What version of MacOS and Safari are y'all using?

**Comment by edewit** [comment]
My laptop is old it's still on Catalina 10.15.7 with Safari 14.1.2 so that could be the problem

**Comment by edewit** [comment]
it wasn't the browser version the behaviour difference was between a prod build and a dev build of the site found the regex responsible for this error in the DownloadDialog

**Comment by edewit** [comment]
thanks @jaynmfs we already discovered the reason for the difference, I upgraded my laptop to the latest version and still had the same error. I found that the difference was between a development build and a production build and where the error is #1829 fixes this error
