### ISSUE TITLE
[UX Review] Some fine-tuning of Groups-member

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-admin-ui#1807]
### Describe the bug

There is some fine-tuning of the Members tab inside the Groups details page as shown in the screenshot below. Please check them.
<img width="1144" alt="Screen Shot 2021-12-30 at 11 15 05 AM" src="https://user-images.githubusercontent.com/53931519/147719219-3a5ec5ff-7b0f-4e85-a032-da4825c6d2b2.png">
1. There is a search box for users to search for the members in the table.
2. Put the checkbox in front of the primary button namely "Add member". 

### Version

New admin UI

**Comment by ssilvert** [comment]
I made this high priority because if there is a large number of users (which is common), it will be very hard for the user to complete the task without a search function.

**Comment by xianli123** [comment]
Yes, this issue should be at a high impact level. Thanks.

**Comment by edewit** [comment]
The current API doesn't support a search

**Comment by xianli123** [comment]
We can remove the search bar for now. Once the feature is supported by the backend, we can implement it. Does it make sense?
