### ISSUE TITLE
[UX Review] Realm select dropdown options should include the current realm

### ISSUE THREAD

**Issue by yih-wang** [keycloak/keycloak-admin-ui#1825]
### Describe the bug

When there're more than 5 realms, the first three options show the recently used realms, the other realms are listed in alphabetical order. The current realm should also be included in it.

This is missing in the current implementation.

### Version

15.0.1

### Expected behavior

![image](https://user-images.githubusercontent.com/23331885/148190178-3ae8acab-8ef5-44f0-92ad-7f81af987c5c.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/23331885/148189894-b47d72c6-f684-44b6-a2c7-727b2800b08d.png)

**Comment by edewit** [comment]
@yih-wang so this "Recent" label should be removed? Is that all that needs to be done? It's strange because in the marvel it has these recent labels:
![image](https://user-images.githubusercontent.com/51133/150094393-59d55561-8c9c-4012-8939-c05a11ea2de3.png)
