### ISSUE TITLE
Fine Grained Permission Tab

### ISSUE THREAD

**Issue by varolemre** [keycloak/keycloak-admin-ui#1853]
### Description

Hi. Will the Fine Grained Permission feature be added? I need to give permission based on groups or users. 

### Motivation

Fine grained permissions are very important for manage our admins.

**Comment by jonkoops** [comment]
@ssilvert I believe you are best qualified to answer this question. Do we intend to add this functionality?

**Comment by ssilvert** [comment]
@jonkoops @varolemre I expect that we will have this functionality in some form.  It should be at least as good as what we have in the old UI, but we may do something more comprehensive.  Hopefully, decisions will be made soon.
