### ISSUE TITLE
Empty modal is shown when Filter Protocol By SAML is selected

### ISSUE THREAD

**Issue by ikhomyn** [keycloak/keycloak-admin-ui#1876]
### Describe the bug

In **Clients** -> **Clients scopes** -> **Add client scope modal** empty modal is shown when FIlter by Protocol -> SAML is selected (No SAML items should be available in the list)

### Version

Keycloak 16.1.0 (WildFly Core 18.0.0.Final)

### Expected behavior

Should allow to select back Filter By Name or other and items should be listed.

### Actual behavior

Empty modal is shown instead, no list items, no filter buttons.

### How to Reproduce?

1. Go to  **Clients** -> any client ID details -> **Clients scopes**
2. Click **Add client scope modal**
3. Select dropdown filter item Protocol with subitem SAML in modal
4. Empty modal appears, no list items and no filter dropdown elements are present.

**Comment by ssilvert** [comment]
Thanks for the bug report @ikhomyn.

**Comment by edewit** [comment]
same as #1911

**Comment by ssilvert** [comment]
@edewit Can we close this one now?
