### ISSUE TITLE
Opening an event with the middle button opens a tab that never loads

### ISSUE THREAD

**Issue by Aboullos** [keycloak/keycloak-admin-ui#1886]
### Describe the bug

Opening an event with the middle button opens a tab that never loads, but if the user of the event is left-clicked the page load fast

### Version

16.1.0

### Expected behavior

A new tab is opened loading the user details

### Actual behavior

An ever loading tab is opened

### How to Reproduce?

Use the middle button of the mouse to open a user detail from the event screen

**Comment by edewit** [comment]
is this still a issue? I couldn't reproduce it

**Comment by Aboullos** [comment]
It looks like it is fixed now
