### ISSUE TITLE
Update admin console documentation links

### ISSUE THREAD

**Issue by mfrances17** [keycloak/keycloak-admin-ui#1893]
### Describe the bug

This is a follow-up to add new doc links for the **Learn more** links that appear on all landing pages of the new admin console, which were added in https://github.com/keycloak/keycloak-admin-ui/pull/1747.

**How to update links**
This is the file that contains all of the help URLs that need to be updated to the latest docs:
`src/help-urls.ts`

Currently, the file contains links to the closest match in the existing docs on keycloak.org. The admin guide main URL is listed at the top of the page:

`const adminGuide = "https://www.keycloak.org/docs/latest/server_admin/index.html";`

And each of the URLs is a specific anchor within that main URL, e.g.:

`clientsUrl: ${adminGuide}#assembly-managing-clients_server_administration_guide,`

So you would just need to edit the one adminGuide URL at the top of the page with the latest admin guide's index.html, and each of the 11 landing page URLs with the latest anchors.

Also, there are 5 landing pages that are missing descriptions at the top of the page. For these, you could just edit the "Placeholder for..." strings in these files:

src/authentication/messages.ts
`authenticationExplain: "Placeholder for authentication explanation.",`

src/groups/messages.ts
`groupsDescription: "Placeholder for authentication explanation.",`

src/realm-settings/messages.ts
`realmSettingsExplain: "Placeholder for realm settings explanation.",`

src/sessions/messages.ts
`sessionExplain: "Placeholder for sessions explanation.",`

src/user/messages.ts
`usersExplain: "Placeholder for users explanation.",`

**Comment by agagancarczyk** [comment]
hi @ssilvert is it expected that the URL for the adminGuide going to change for keycloak 19? The URL seems quite generic `https://www.keycloak.org/docs/latest/server_admin/index.html` and it has `\latest` so I think once keycloak 19 is released the documentation will be using the same URL. Thus, we won't need to make any changes to the URL definition in our admin console. I have checked all the links and they are pointing correctly to the latest keycloak 18 documentation. 

As for the 5 landing pages that are missing descriptions at the top of the page, this is still true. Could you please advise who should provide these descriptions so that I can add them to the admin console? 

Thanks!

**Comment by ssilvert** [comment]
@agagancarczyk Thanks for checking this out.

We could get Andy to come up with text for those missing subscriptions.  But it might be quicker if you just come up something yourself and then ask Andy to review.

**Comment by agagancarczyk** [comment]
Thanks @ssilvert . @andymunro could you please review the following subheading texts? I'll add them to each section once approved. Thanks

- `Users` subheading text - `Users is a space for searching, creating, editing and deleting users.`
- `Groups` subheading text - `Groups is dedicated to managing the common set of attributes and role mappings for each user through actions such as group search, creation, edit, child-parent reorganization and deletion.`
- `Sessions` subheading text - `Sessions records and lists user sessions for each user and remembers each client visited by the user within the session.`
- `Realm settings` subheading text - `Realm settings is for managing objects, including users, applications, roles, and groups.`
- `Authentication` subheading text - `Authentication allows for configuring and managing different credential types.`

**Comment by andymunro** [comment]
@agagancarczyk, @ssilvert 
Actually, I would like to suggest revisions for all the text.  Let me know what you think:

Clients subheading text - 
Clients are applications and services that can request authentication of a user.

Client scopes subheading text 
Client scopes are a common set of protocol mappers and roles that are shared between multiple clients.

Realm roles subheading text
Realm roles are the roles that you define for use in the current realm.

Users subheading text
Users are the users in the current realm.

Groups subheading text
A group is a set of attributes and role mappings that can be applied to a user. You can create, edit, and delete groups and manage their child-parent organization.

Sessions subheading text -
Sessions are sessions of users in this realm and the clients that they access within the session.

Events subheading text
Events are records of user and admin events in this realm. To configure the tracking of these events, go to Event configs (keep the link currently used for Events config).

Realm settings subheading text
Realm settings are settings that control the options for users, applications, roles, and groups in the current realm.

Authentication subheading text
Authentication is the area where you can configure and manage different credential types.

Identity providers subheading text
Identity providers are social networks or identity brokers that allow users to authenticate to Keycloak.

User federation subheading text
User federation provides access to external database and directories, such as LDAP and Active Directory.

**Comment by agagancarczyk** [comment]
Thanks @andymunro I really like your version of subheadings. Great job! @ssilvert wdyt?

**Comment by ssilvert** [comment]
@agagancarczyk Andy is the word man.  Let's use his text.

**Comment by andymunro** [comment]
Okay, thanks, @agagancarczyk and @ssilvert.  However, I should have made databases plural in the last one.

**Comment by agagancarczyk** [comment]
This can now be closed @ssilvert . Thanks
