### ISSUE TITLE
[UX Review] Some fun-tuning of the search form in the Admin events

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-admin-ui#1895]
### Describe the bug

There is some fine-tuning of the search form on the Admin events page as shown in the picture below.

1. The fields overlap tags. It looks wired. So we can change this part.
<img width="1137" alt="Screen Shot 2022-01-20 at 1 46 07 PM" src="https://user-images.githubusercontent.com/53931519/150283326-7c5a4f9c-4b0a-4226-9b89-16eced678ada.png">

2. Add a "Reset" button in the search form.
<img width="567" alt="Screen Shot 2022-01-20 at 10 16 18 AM" src="https://user-images.githubusercontent.com/53931519/150283686-9fa40b57-9a1b-4685-9568-b0e75beca91d.png">

### Version

New admin UI

**Comment by dominikkawka** [comment]
Hey @xianli123, I'm not quite sure what you mean by "The field overlaps tags", What info would go into the tags also? Thanks

**Comment by xianli123** [comment]
@dominikkawka Sorry, I pasted the wrong screenshot. The first one seems to have been fixed. Please skip it over and just need to fix the second one. Thanks.

**Comment by dominikkawka** [comment]
@xianli123 I checked the second issue and there seems to be a reset button already.

![image](https://user-images.githubusercontent.com/31955648/182566252-d22af5fb-4e54-43c0-9da7-f0f072a58da9.png)

![image](https://user-images.githubusercontent.com/31955648/182566107-6786a94f-1010-4f27-a8ab-b56364e5ddea.png)

**Comment by jonkoops** [comment]
@xianli123 @dominikkawka can this issue be closed?

**Comment by xianli123** [comment]
@jonkoops yes, let me close it.
