### ISSUE TITLE
[UX Review] Client policies > profile > executor details: the changes cannot be saved

### ISSUE THREAD

**Issue by yih-wang** [keycloak/keycloak-admin-ui#1900]
### Describe the bug

- I tried to change the configuration of the executor. The changes won't be saved whether I changed them during creation or edit.
- Breadcrumb is not correct in the details page. Should be "Realm settings > Client policies > [profile name] > Executor details"
- Breadcrumb is not correct in the creation page. Should be "Realm settings > Client policies > [profile name] > Add executor"

![image](https://user-images.githubusercontent.com/23331885/150306451-95d0b794-9b57-4757-b339-7fe2ae8dd3ad.png)

### Version

15.0.2

**Comment by edewit** [comment]
this is also fixed with https://github.com/keycloak/keycloak-admin-ui/pull/2070
