### ISSUE TITLE
Policy tab is missing

### ISSUE THREAD

**Issue by yagoubgrine** [keycloak/keycloak-admin-ui#1921]
### Describe the bug

Hi,
I'm traying the new UI, and I can't find the policy tab under the authorization tab?

Kind Regards.

### Version

16.1.0

### Anything else?

Admin UI versionbd28a912dd40839403ae3d538920a6781e516a04

**Comment by ssilvert** [comment]
Hi @yagoubgrine.  This was just recently added.  You would need the latest version to see it.

https://github.com/keycloak/keycloak-admin-ui/pull/1884

Thanks for the feedback.
