### ISSUE TITLE
[UX Review] Add SAML provider: import config from file shouldn't support "svg" format

### ISSUE THREAD

**Issue by yih-wang** [keycloak/keycloak-admin-ui#1944]
### Describe the bug

Seems the current file upload only supports selecting a .svg file. Need to reference the old console to decide which type it supports.

![image](https://user-images.githubusercontent.com/23331885/150937988-b12af27e-6bdc-41cf-84d3-08384c7f9a1e.png)

### Version

15.0.2

**Comment by edewit** [comment]
as svg is an xml format this is technically not wrong
