### ISSUE TITLE
Page can’t be found opening new tab from sidebar menu

### ISSUE THREAD

**Issue by ikhomyn** [keycloak/keycloak-admin-ui#1958]
### Describe the bug

When I open a new tab of any section from sidebar menu, It opens to page can’t be found

### Version

Keycloak 16.1.0 (WildFly Core 18.0.0.Final)

### Expected behavior

Should open a new tab with expected link, example: http://localhost:8080/#/master/client-scopes

### Actual behavior

Getting new tab with link: http://localhost:8080/master/client-scopes, with message page not found

### How to Reproduce?

1. Right click on **Clients Scopes** in left menu -> Open link in new tab
2. Browser will open new tab with different not reachable link

### Anything else?

It missing #/ in the link

**Comment by ssilvert** [comment]
Thanks @ikhomyn
