### ISSUE TITLE
[UX Review] Authentication > Required actions: the "Set as default action" should always be Disabled off when the "enabled" is Off

### ISSUE THREAD

**Issue by yih-wang** [keycloak/keycloak-admin-ui#1964]
### Describe the bug

Now, only the last three actions act the correct way by default. However, after enabling and disabling the actions again, the "Set as default action" is not disabled anymore.

### Version

15.0.2

### Expected behavior

The correct behavior looks like this - "set as default action" is always disabled when "enabled" is off - this applies to all the required actions
![image](https://user-images.githubusercontent.com/23331885/151341007-4f1d1eec-2af2-47dd-913e-26e59f575720.png)
![image](https://user-images.githubusercontent.com/23331885/151341082-ee358eee-f8ef-4c47-9926-7137ff7c9be3.png)

**Comment by edewit** [comment]
I think it's correct disabled is only the initial state when it's not register after you register it and turn it off it remains registered.
