### ISSUE TITLE
[UX Review] Add 3 new settings in the Advanced tab of OIDC client

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-admin-ui#1969]
### Describe the bug

In the latest version, there are some new settings named Logo URL, Policy URL, and Terms of service URL. In the new design, these 3 settings can be moved to the group "**Fine grain OpenID Connect configuration**" as shown in the screenshot below. 
<img width="489" alt="Screen Shot 2022-01-28 at 5 28 43 PM" src="https://user-images.githubusercontent.com/53931519/151521988-f6afbe42-0f80-44db-b42a-bd06bb350d87.png">

### Version

New admin UI

**Comment by xianli123** [comment]
Hi @edewit I reopened this issue because I found these 3 new settings are missed in the latest UI. It's weird that I remember we have already fixed this issue. Could you please recheck this issue?

**Comment by edewit** [comment]
This is already done: 
![image](https://user-images.githubusercontent.com/51133/182802123-1d1e8434-0694-4186-9ba2-81909c2638a3.png)

**Comment by xianli123** [comment]
Oh, sorry, I got the SAML and OIDC mixed up. I will create a new issue for SAML advanced settings.
