### ISSUE TITLE
The type of Builtin Protocol Mappers "groups" should be "Group Membership" not "User Realm Role".

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-admin-ui#1974]
### Describe the bug

See https://issues.redhat.com/browse/KEYCLOAK-13331

### Version

17.0.0-SNAPSHOT

**Comment by edewit** [comment]
The new design no longer has this dialog:
![image](https://user-images.githubusercontent.com/51133/158344747-6d52f465-8236-4c33-9db1-97b5600b2699.png)
