### ISSUE TITLE
includeInAccessTokenResponse.label and includeInAccessTokenResponse.label.tooltip english messages are missing

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-admin-ui#1993]
### Describe the bug

Same bug exists in both new and old UI.  See https://github.com/keycloak/keycloak/issues/9364.

### Version

17.0.0-SNAPSHOT

**Comment by kherock** [comment]
I recently enabled the new Admin UI and am seeing this in Keycloak 19.0.3. Should I open a new issue?

**Comment by jonkoops** [comment]
@kherock if this issue still persists in a [nightly version](https://github.com/keycloak/keycloak/releases/tag/nightly), then yes. If it's not reproducible it will be fixed in the next major version, which is a couple of weeks away.
