### ISSUE TITLE
Help text missing in User Fed --> Kerberos --> Settings 

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-admin-ui#2003]
### Describe the bug

Help text missing in User Fed --> Kerberos --> Settings 
Also missing for User Fed --> LDAP --> Settings

A few fields do have help text, but most are missing.

### Version

17.0.0-SNAPSHOT

**Comment by edewit** [comment]
This is no longer an issue correct?

**Comment by mfrances17** [comment]
All of the help text was working originally, then a random PR did a search and replace for user --> users which broke the help Ids. But I fixed them as part of https://github.com/keycloak/keycloak-admin-ui/pull/2038 so this can be closed.
