### ISSUE TITLE
[UX review] Add 2 new fields in General settings of SAML client

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-admin-ui#2026]
### Describe the bug

There are 2 new fields that can be added in the General settings in the SAML client settings page, namely, **_Always Display in Console_** and **_Front channel logout_**. The design is shown in the screenshot below. Notice that the **_Front channel logout_** should be ON by default. Please check it and fix the issue. Thanks

<img width="704" alt="Screen Shot 2022-02-08 at 3 33 06 PM" src="https://user-images.githubusercontent.com/53931519/152940622-55dc8d52-df50-4b4a-90d9-7f01af89013f.png">
 

### Version

New admin UI

**Comment by jenny-s51** [comment]
Hi @xianli123 ! There seem to be some conflicting details between this issue and #1968. 

I've added the "always display" switch in #2165, and added the "front channel logout" switch + field under logout settings in #2164. 

Is this the expected appearance/behavior? Please kindly review when you have a moment. 🙂

**Comment by xianli123** [comment]
> There seem to be some conflicting details between this issue and https://github.com/keycloak/keycloak-admin-ui/issues/1968. 

Yes, I reviewed these 2 issues and found that their descriptions of "front channel logout" are conflicted.

> Added the "front channel logout" switch + field under logout settings in https://github.com/keycloak/keycloak-admin-ui/pull/2164.

That is right. "Front channel logout" should be put in the **Logout settings**.

**Comment by xianli123** [comment]
Hi @jenny-s51 ， I am sorry for the late reply. 
> There seem to be some conflicting details between this issue and https://github.com/keycloak/keycloak-admin-ui/issues/1968.

I've checked these 2 issues. There is no conflict between them. Because this issue is based on the SAML client, and the https://github.com/keycloak/keycloak-admin-ui/issues/1968 is based on the OIDC client. SAML client and OIDC client have different settings. So please fix this issue for SAML client. Thanks.

**Comment by xianli123** [comment]
Hi @jenny-s51 , in the SAML client, "always display" and "front channel logout" should be put in the General settings. In OIDC client, it has different case. This issue is based on the SAML client, so we can fix this issue for SAML client.

**Comment by jenny-s51** [comment]
Awesome, thank you for clarifying @xianli123 !
