### ISSUE TITLE
add support for CIBA

### ISSUE THREAD

**Issue by edewit** [keycloak/keycloak-admin-ui#2045]
### Describe the bug

CIBA is a feature that adds a couple of fields to client and a extra tab on authentication that is currently not supported by this console.

**Comment by jonkoops** [comment]
@edewit can you add a priority to this issue?

**Comment by edewit** [comment]
I don't know how important this is maybe @ssilvert has an idea

**Comment by ssilvert** [comment]
@edewit If you can do it in the old UI, but not the new UI then it's considered high impact.

**Comment by edewit** [comment]
But it's only there when you enable a feature flag

**Comment by ssilvert** [comment]
I'm pretty sure CIBA support will need to be there, which makes it high impact.  But @stianst would know for sure.  
@stianst WDYT?

**Comment by stianst** [comment]
It must be included prior to making the new console the default, but that applies to everything. So, not quite sure what is being discussed and priorities relative to what.
