### ISSUE TITLE
[UX Review] Authentication needs to update the behavior of binding flow (set as default)

### ISSUE THREAD

**Issue by yih-wang** [keycloak/keycloak-admin-ui#2046]
### Describe the bug

Considering the flow type (column) hasn't been introduced in this release, the previous binding flow (set as default) behavior doesn't work anymore. Because the user cannot just simply set a flow as the default flow, but also need to point out which flow type they want to set. Here is the new design that fixes this issue - 

https://marvelapp.com/prototype/bh91013/section/1557433

(Note: this feature equals to the Bindings tab in the old console)

### Version

15.0.2

**Comment by edewit** [comment]
according to the [mavel](https://marvelapp.com/prototype/bh91013/screen/85125471) the action context menu will now be the same but currently it also has the edit info:

![image](https://user-images.githubusercontent.com/51133/156165110-d113b5c9-4c1a-496d-9b68-96f491dabd8e.png)

I think what you would want to change is the "Set as Default" option into the "Bind flow" option right?

**Comment by yih-wang** [comment]
@edewit Exactly. The marvel screen only shows the case for the built-in flow.
