### ISSUE TITLE
[UX Review] Realm roles / client roles / User registrations: the modal of adding (associated) roles is not correct

### ISSUE THREAD

**Issue by yih-wang** [keycloak/keycloak-admin-ui#2102]
### Describe the bug

1. The modal should default include all the roles (realm roles and client roles). Now it only shows the realm roles. The order of all the roles can reference the "Service account roles" tab of client - realm roles go first. Then the client roles follow the alphabetical order of client name, then role name.
2. The behavior of the filter is not correct (the correct behavior can also reference the "Service account roles") - when opening the filter, the options should include all the client names & realm. Also the filter and the search bar should have a space between each other. See the following screenshot. 
![image](https://user-images.githubusercontent.com/23331885/154022517-7d40acaa-a594-494c-90e2-593b16481e40.png)

### Version

16.0.1

**Comment by edewit** [comment]
@yih-wang I think the dropdown only shows the clients that have roles that is why not all clients are show

**Comment by yih-wang** [comment]
@edewit The screenshot I posted above shows the correct case. The dropdowns that need to be updated look like this - 

![image](https://user-images.githubusercontent.com/23331885/155993207-5b0dd49d-b1ff-4f65-a2f4-03243905e045.png)

The filter doesn't include any clients, but can only switch between filter 
by clients or filter by roles.

**Comment by edewit** [comment]
this screen is a custom component that is used in multiple places, do you want it to be changed to this in all of those places?

**Comment by yih-wang** [comment]
@edewit yes that will be nice.

**Comment by edewit** [comment]
this is already done
