### ISSUE TITLE
[UX Review] The new added Home URL will be missing in the  client table

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-admin-ui#2137]
### Describe the bug

As shown in the screenshot below, the client table can't display the value of the Home URL after adding the Home URL and saving it in the OIDC client settings page,  So please check and fix it. 

<img width="944" alt="Screen Shot 2022-02-23 at 1 38 05 PM" src="https://user-images.githubusercontent.com/53931519/155267165-45fc7dd9-9668-4731-933b-7ca61a7d5aae.png">

### Version

New admin UI

**Comment by ssilvert** [comment]
@xianli123 I don't understand this.  Your screen shot shows the URL.  Are you saying it disappears after you save?

**Comment by xianli123** [comment]
Hi @ssilvert  I created a picture as shown in the screenshot below. After users add the Home URL and save it in the Settings page, the Home URL  should appear in the client list. But the Home URL is now missing from the client. The saved Home URL should be displayed in the client list once the Home URL is added.
<img width="870" alt="Screen Shot 2022-02-24 at 10 18 44 AM" src="https://user-images.githubusercontent.com/53931519/155445504-ffb191a5-a9d8-4374-836a-2ed02d03daf6.png">

**Comment by ssilvert** [comment]
@xianli123 I understand now.  Thanks.

**Comment by xianli123** [comment]
My pleasure. 😁
