### ISSUE TITLE
Missing attributes to support step up authentication

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-admin-ui#2187]
### Describe the bug

We need to add attributes to support step-up authentication.  These have already been added in the latest version of the old Admin UI.

Here is snippet of email from @mposolda :

2) Step-up authentication: There are already some configuration
properties in the keycloak "main" branch. I've tagged you in some PRs
before, but not sure if you saw this and PRs are merged already. The
changes are:

- "ACR to LoA Mapping" in the realm settings
- Properties "ACR to LoA Mapping" and "Default ACR Value"in the client
settings initial tab (The one which is available on the URL like for
example
http://localhost:8081/auth/admin/master/console/#/realms/test/clients/2e90cf42-6bf1-4564-9572-6de5be0efccc
) . It is packed in the "Advanced Settings" part of that page.

Those properties are already available in the keycloak main branch, but
there will be feature check added (properties will be available just
when explicitly enabled by feature "step-up-authentication").

### Version

18.0.0-SNAPSHOT

### Screen Design

[Marvel](https://marvelapp.com/prototype/17414bf9/screen/86094456)

**Comment by xianli123** [comment]
Hi @ssilvert  I found that this issue mentioned a new feature regarding Authentication. Should I provide a design for this feature? And what is your plan for this feature?

**Comment by ssilvert** [comment]
@xianli123 I believe this just comes down to the addition of a few fields, so we don't need an all new design.  But it might be nice if the existing design is updated.

**Comment by xianli123** [comment]
@ssilvert Ok, I can update the design of this new feature. I've tried to initiate the Keycloak 18.0 release but failed. So I can't see this feature in my current console. Do you have relevant requirements and screen shots of it? Or wait until version 18 is released to implement this feature? Thanks.

**Comment by xianli123** [comment]
Ok. I've tried to build the 18.0 version based on this doc but failed. I will try it again. Thanks.

**Comment by ssilvert** [comment]
@xianli123 If you are still having trouble we can schedule a video chat and I will walk you through it.  I do think you will need to be able to build it yourself as long as new changes are still allowed in the old UI.

**Comment by xianli123** [comment]
Ok, thanks. I've already seen Haley's demo. I will try it by myself. And I think I can provide some designs.
