### ISSUE TITLE
Update Credentials tab to support Client Secret Rotation feature

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-admin-ui#2188]
### Description

This is not implemented in the old Admin UI yet, but we need to work with @marcelomrwin to make sure it is added to new Admin UI as soon as he is ready.

 **"Client Secret rotation" feature -**
https://github.com/keycloak/keycloak-community/blob/main/design/client-secret-rotation.md

It will affect the "Credentials" tab of the "client" in the current
admin console. Currently there is client secret and the button
"Re-generate secret" . There will be few more things optionally shown on
this page like:

- Client secret expiration time

- Old client secret

- Old client secret expiration time

This change is not in the keycloak "main" yet

**Comment by xianli123** [comment]
Hi @ssilvert 

> Some additional options we may want to add in the future includes:

- Allow supplying the secret through APIs. If disabled all client secrets will be generated by Keycloak.
- Length/complexity of the client secrets if the above is enabled
- Enable/disable hashing of secrets, and configuring the hashing algorithm

I found there are some other settings in the future. At this moment, we don't need to take these settings into account. Right?

**Comment by edewit** [comment]
I can't get this feature to work, this is what I've done:
1. added the feature flag to keycloak start script `client-secret-rotation`
1. added the secret-rotation to the profile:
![image](https://user-images.githubusercontent.com/51133/167585404-94e6c6ba-c7d9-4073-a763-9125174b8f32.png)
1. then I should see this on the credentials screen... but I don't:
![image](https://user-images.githubusercontent.com/51133/167586175-e86d65f3-f591-4105-883b-3880dc8808fa.png)

**Comment by marcelomrwin** [comment]
Hi @edewit, According to the [XYZ](https://www.keycloak.org/docs/latest/server_admin/index.html#_secret_rotation) documentation, after setting the rotation policy was a new secret generated?

![image](https://user-images.githubusercontent.com/4205291/167598219-b901842d-6365-4c60-914b-16fe7ed2d8f2.png)

**Comment by edewit** [comment]
yes I did that, but it didn't help still don't see the the expire time message nor is it in the server response
