### ISSUE TITLE
[UX Review] Some fine-tuning of the Password policy in the Authentication policy page

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-admin-ui#2230]
### Describe the bug

There is some fine-tuning of the Password policy page as shown in the screenshot below.

<img width="1053" alt="Screen Shot 2022-03-11 at 10 20 55 AM" src="https://user-images.githubusercontent.com/53931519/157789853-6e36c21d-1cbe-4c1c-83b4-69f2ef901322.png">

1. Each label of the fields should have a tooltip.
2. **Hashing Algorithm** should be a dropdown.

For more details please refer to the design link. https://marvelapp.com/prototype/5ifgiai/screen/75687755

### Version

Admin new UI

**Comment by edewit** [comment]
There are no help texts for these in the old console, if you have them I can add them

**Comment by xianli123** [comment]
Hi @edewit , I don't have the tooltips for them. If it's possible, we can ask Andy for help. What do you think?

**Comment by edewit** [comment]
Yes I can't just invent some text for them, what should the values of hash algorithm be? It's a text field in the old console as well

**Comment by xianli123** [comment]
Ok, we can ask Andy for help. I will email Andy for the tooltips. As for the Hash algorithm, we can use the text field for now. Thanks

**Comment by xianli123** [comment]
Hi @edewit , there are some suggestions from Andy as listed below. Here is the doc named [Policy Tooltips](https://docs.google.com/document/d/18SlL-5N-9-fhbkehfSmbvEIYHW83xYAIegqAeiWhtpw/edit?usp=sharing). Please check them and add the tooltips for the tags. Thanks! 

>  == Expire password
> The number of days the password is valid before a new password is required.
> 
> == Hashing iterations
> The number of times a password is hashed before storage or verification. Default: 27,500.
> 
> == Not recently used
> Prevents a recently used password from being reused.
> 
> == Password blacklist
> Prevents the use of a password that is in a blacklist file.
> 
> == Regular expression
> Requires that the password matches one or more defined regular expression patterns.
> 
> === Minimum Length
> The minimum number of characters is required for the password.
> 
> == Not username
> The password cannot match the username.
> 
> == Not email
> The password cannot match the email address of the user.
> 
> == Special characters
> The number of special characters is required in the password string.
> 
> == Uppercase characters
> The number of uppercase letters required in the password string.
> 
> == Lowercase characters
> The number of lowercase letters is required in the password string.
> 
> == Digits
> The number of numerical digits required in the password string.
> 
> == Hashing algorithm
> Applies a hashing algorithm to passwords, so they are not stored in cleartext.
> 
> ==  Maximum Length
> The maximum number of characters allowed in the password.
