### ISSUE TITLE
[UX Review] There is no "Create attribute" page in the User profile function

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-admin-ui#2248]
### Describe the bug

As shown in the screenshot below, there is no "Create attribute" page on the User profile page. Here is the design link, FYI https://marvelapp.com/prototype/5eed532/screen/82246809. 

<img width="925" alt="Screen Shot 2022-03-14 at 11 30 09 AM" src="https://user-images.githubusercontent.com/53931519/158100191-69f5781d-c8a8-4e65-9ad5-79cb421f7de4.png">

### Version

Admin new UI

**Comment by xianli123** [comment]
The attribute edit page is the same as the creation page.

**Comment by xianli123** [comment]
Thanks @agagancarczyk @jenny-s51 !

**Comment by agagancarczyk** [comment]
hi @xianli123 this is now implemented in #2278 and #2279. Once merged you'll be able to test it and provide feedback. In the meantime, I'm going to work on editing newly created attributes as per #2268. Thanks

**Comment by xianli123** [comment]
Sound great. Thank you.

**Comment by edewit** [comment]
this was just not done yet closing
