### ISSUE TITLE
The code that processes `route-config.ts` needs to be able to handle multiple roles.

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-admin-ui#225]
The code that processes `route-config.ts` needs to be able to handle multiple roles.  And we don't do anything with subroutes right now anyway so I'm not sure how we need to check them.  We don't have any of that yet, but I believe that you should still be able to code it like this:  
```suggestion
    access: ["view-realm", "view-users"],
```

_Originally posted by @ssilvert in https://github.com/keycloak/keycloak-admin-ui/pull/217#discussion_r524545274_

**Comment by ssilvert** [comment]
We probably need some sort of interceptor that checks access when you try to navigate to a page.

**Comment by ssilvert** [comment]
Not sure if this is still an issue, but we need to test it out before 1.0 is released.

**Comment by jonkoops** [comment]
@ssilvert I created a fix in #946, do we know which routes we want to secure this way?
