### ISSUE TITLE
[UX Review] Update the "Search form" on the Authorization-Resources page

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-admin-ui#2282]
### Describe the bug

There is some fine-tuning about searching for resources in the client authorization page, as shown in the screenshot below. Here is the design proposal: https://marvelapp.com/prototype/6a7eeb2/section/1578686

<img width="648" alt="Screen Shot 2022-03-17 at 10 25 01 AM" src="https://user-images.githubusercontent.com/53931519/158725010-8a4acfac-707a-43d3-b1c4-454c7340d54a.png">

1. The type should be a dropdown.
2. The "Associated permissions" is missing.
3. The "Clear" button should be the "Reset" button. Clicking the "Reset" button will clear all the criteria.

### Version

New admin UI

**Comment by edewit** [comment]
We can only do the filters that are available on the old console as any other fields need to be added to the backend.

**Comment by xianli123** [comment]
Ok, I see. We can fix No.1 and No.3. Does it make sense?

**Comment by xianli123** [comment]
So will it spend a lot of time to load all resources?

**Comment by edewit** [comment]
it doesn't make sense, we have pagination in the table, but to do a search on type we load all resources?

**Comment by xianli123** [comment]
Ok, I see. If so, we can keep it as the same as what we have now. Thanks.
