### ISSUE TITLE
[UX Review] The option "Bind flow" is missing in the flow details page

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-admin-ui#2320]
### Describe the bug

In the Browser flow details page, there should be an option named "Bind flow" in the Action menu list. In the current UI, this option is missing. So please add this option in the Action menu. The same thing happens to the **Direct grant, Registration, Reset credentials and Docker auth.**

<img width="1132" alt="Screen Shot 2022-03-22 at 4 34 56 PM" src="https://user-images.githubusercontent.com/53931519/159440411-79ff1e32-279c-43fe-b164-0c2f12b5af4c.png">

### Version

Admin new UI

**Comment by edewit** [comment]
It's not there as this Flow is already bound, if it's not in use the bind flow option is there:
![image](https://user-images.githubusercontent.com/51133/168747122-cc41067e-b21e-415e-be12-56894a8ae33a.png)

**Comment by xianli123** [comment]
Oh, I see. That makes sense. Let's close this issue.
