### ISSUE TITLE
"Decision strategy" at Authorization > Settings displays wrong value

### ISSUE THREAD

**Issue by flipp5b** [keycloak/keycloak-admin-ui#2372]
### Describe the bug

I have a client with enabled fine-grained authorization support. Decision strategy is set to "Affirmative" (using old UI). But it's displayed as "Unanimous" in the new UI:
![Screenshot from 2022-03-30 14-50-38](https://user-images.githubusercontent.com/5507566/160828446-917779d0-a66d-4eaf-a0f9-bce173b0ed95.png)

Old UI:
![Screenshot from 2022-03-30 14-37-52](https://user-images.githubusercontent.com/5507566/160830018-ac191ae5-3249-43f5-969e-b47e8470f8b3.png)

Values received from server:
![Screenshot from 2022-03-30 14-41-36](https://user-images.githubusercontent.com/5507566/160830266-d3d6e8d3-6ad6-4f42-9045-c2d8015033a5.png)

### Version

17.0.1

**Comment by ssilvert** [comment]
@flipp5b Thanks for reporting this.  I've reproduced the issue on my end.

FYI, for whoever looks at this, you don't need to enable fine-grained authorization to see the issue.  Just create a client and enable Authorization.  Any time Decision strategy is set to Affirmative, the UI always defaults to Unanimous.
