### ISSUE TITLE
"Group" field is blank for existing hardcoded-ldap-group-mapper

### ISSUE THREAD

**Issue by flipp5b** [keycloak/keycloak-admin-ui#2381]
### Describe the bug

We have an LDAP mapper of type hardcoded-ldap-group-mapper with a specified "group" value. In the new admin UI, the "group" field is displayed as empty.

### Version

17.0.1

**Comment by ssilvert** [comment]
Thanks for reporting this @flipp5b. 

I have verified the bug.
