### ISSUE TITLE
Fine-grained Permissions Screens

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-admin-ui#2402]
### Description

This issue is only for the screens portion of [Fine Grained Permissions](https://www.keycloak.org/docs/latest/server_admin/#_fine_grain_permissions) functionality.  

We need screens that are similar to what we have in the old Admin UI so that the user can configure fine grained permissions.

Updates to the UI that restrict user access based on these permissions is a separate task handled by [a separate issue](https://github.com/keycloak/keycloak-admin-ui/issues/2403).

**Comment by xianli123** [comment]
Hi @ssilvert I am researching this feature based on the documentation and recorded some info in a doc. Here is the link: https://docs.google.com/document/d/1nGWshTYK5CQajgVesyUOcG2_WOeO65PfjLnxKp4lQwA/edit?usp=sharing  It includes some questions that need to be answered by developers.
