### ISSUE TITLE
User page not loaded in admin console v2 having only roles "view-users, manage-users"

### ISSUE THREAD

**Issue by joggeli34** [keycloak/keycloak-admin-ui#2504]
### Describe the bug

When using a user which has the roles from realm-management "manage-users" and "view-users" the user-page is not loaded in the admin-console v2. Only a spinner is shown.

The group-page is shown and the groups are listed, but they can not be edited. Also no new group can be created. 

![image](https://user-images.githubusercontent.com/34470368/164741558-c051b06b-7987-4659-9a27-c47e0dbbcb3d.png)

With the old admin-console, it works.

### Version

18.0.0-legacy

### Expected behavior

With the two roles, the user should be shown and be editable, same for the groups.

### Actual behavior

Users are not shown, groups are not editable.

### How to Reproduce?

Create a user only having the client-roles "manage-users" and "view-users" from the realm-management

**Comment by ssilvert** [comment]
@edewit I tracked this one down to UsersSection.tsx.  If the user does not have "view-realm" access then the call to /components?type=org.keycloak.storage.UserStorageProvider will fail.

It looks like you are using that call to figure out if there is a federation provider or not.  I suggest that if the user does not have "view-realm" access then just drop back to the behavior where we make the administrator query for users.

While you are in that code, I suggest that you add to the Empty State message.  It currently says, "This realm has a federated provider. Viewing all users may cause the system to slow down. Please search for a user above."  Suggest change to "This realm has a federated provider. Viewing all users may cause the system to slow down, but it can be done by searching for "*". Please search for a user above."

**Comment by edewit** [comment]
@joggeli34 That you can view groups is because view-users is a composite from view-groups
