### ISSUE TITLE
Show Authentication Flow-Bindings in Flow list

### ISSUE THREAD

**Issue by thomasdarimont** [keycloak/keycloak-admin-ui#2509]
### Description

After creating a custom flow and binding it to a flow-type (e.g. Browser Flow)
Actual: ... the user does not see the Flow-Type of a particular flow.
Desired: ... the user should see the Flow-Type of a particular flow.

The flow type could be either shown as an additional "tag" or a column in the flows list.

### Discussion

https://github.com/keycloak/keycloak/discussions/11648

**Comment by edewit** [comment]
@thomasdarimont flow type is either `Client Flow` or `Basic Flow` right? You don't see this in the old console either, I'm not sure what you mean that's missing

**Comment by edewit** [comment]
okay didn't get this at first, but now I do you mean that in the new ui you can't see what is the current Browser Flow @xianli123 we could change the "default" label to say the name of the flow or add it WDYT?

Old ui I know "specific" is the Browser Flow:
![image](https://user-images.githubusercontent.com/51133/165703114-5c294950-7a93-4727-af79-27a2f2e4659c.png)
New ui I only know it's a default flow:
![image](https://user-images.githubusercontent.com/51133/165703324-f48777d0-7baa-4f1a-b265-77dd77b2257a.png)

**Comment by thomasdarimont** [comment]
Yes, changing "default" to the name of the target flow-binding makes sense to me.

Sometimes customers create additional authentication flows that are just specific to a number of clients. -> Authentication Flow Overrides (Browser / Direct Grant etc.). I wonder if this could also be reflected somehow on that screen?
A similar thing is "First Broker Login / Post Broker Login" sometimes customers create dedicated first / post broker login flows for Identity Providers. It would also be helpful to see where those flows are used as well.
E.g.:
- "Browser: client1,client2,client3) 
- "First Broker Login: Idp1, Idp2, Idp3) 
Note that this lists could get quote large... so perhaps a dynamic tooltip or a nested list that expands would be helpful here.


But perhaps it would better to have a dedicated column for this

Flow Name | Flow-Binding | Override | Description
First Broker Login (Built-in) | First Broker Login | - | Actions taken after...
Custom Browser | Browser | - | Custom Browser Flow
Client Browser | Browser | Client1, Client2 | Custom Client Login for legacy clients
Custom First Broker Login | First Broker Login | IdP1, IdP2 | ...

**Comment by edewit** [comment]
@thomasdarimont right, but what if there are a lot of clients that this flow is used by? Right now we just do this:
![image](https://user-images.githubusercontent.com/51133/165737071-d1610f56-1564-4979-bea2-f1d5f737084f.png)

**Comment by xianli123** [comment]
We have updated the design and fixed these issues. Please refer to the design link here: https://marvelapp.com/prototype/bh91013/screen/75647039.

**Comment by thomasdarimont** [comment]
Thanks this looks much better :)

Btw. regarding `right, but what if there are a lot of clients that this flow is used by?` I know its not possible yet, but could the links behind "Specific clients" and "Specific Providers" just point to a parameterized search for "clients with that flow" or "providers with that (first broker / post broker) flow"?

**Comment by xianli123** [comment]
@thomasdarimont I see. In the new design, the `Specific clients` and `Specific providers` are hyperlinks. Clicking the link, there will be a modal popup to show the clients or providers as shown in the screenshot below.

<img width="401" alt="Screen Shot 2022-04-29 at 14 24 19" src="https://user-images.githubusercontent.com/53931519/165909577-f6836b3e-d312-47e2-a402-c1503887371e.png">

**Comment by xianli123** [comment]
Thanks for you suggestions.
