### ISSUE TITLE
Make provider information visible in new admin-console

### ISSUE THREAD

**Issue by thomasdarimont** [keycloak/keycloak-admin-ui#2510]
### Description

The old admin console exposed the list of currently used providers in Server Info.
Customers used that information to determine whether certain extensions are available in a Keycloak instance, and potentially
additional information provided via org.keycloak.provider.ServerInfoAwareProviderFactory.

Currently the Server info of the new admin console does not show the list of installed providers.

### Discussion

https://github.com/keycloak/keycloak/discussions/11648

**Comment by xianli123** [comment]
Hi @stianst @ssilvert @edewit Can we put the provider info in a new tab on the dashboard page, as shown in the screenshot below. What do you think?
<img width="925" alt="Screen Shot 2022-04-27 at 18 40 31" src="https://user-images.githubusercontent.com/53931519/165500928-f690207d-9954-4521-ab31-e1735a174cb8.png">

**Comment by thomasdarimont** [comment]
Wow that was quick :) Does this also support search and provider specific information?
![image](https://user-images.githubusercontent.com/314690/165899154-adc6a871-9913-40ce-8dc5-f33d0a443b67.png)

**Comment by edewit** [comment]
ahh no, let's re-open this issue to remind us that this still is needed
