### ISSUE TITLE
Client secret should be masked in admin-ui

### ISSUE THREAD

**Issue by thomasdarimont** [keycloak/keycloak-admin-ui#2512]
### Description

The old and new admin console show the client secret in plain text. This is problematic in demo / review situations.
It would be helpful if the client secet could be masked / hidden like the user password by default in the admin-console.
If administrators really need the plain text value they should be able to "reveal" or just copy the plain text value.

### Discussion

https://github.com/keycloak/keycloak/discussions/11648

**Comment by xianli123** [comment]
Hi @thomasdarimont @ssilvert , I added a visible icon as shown below. In most cases, the secret is hidden. Users can click the visible icon to view the text. Does it make sense?

<img width="960" alt="Screen Shot 2022-04-28 at 15 44 49" src="https://user-images.githubusercontent.com/53931519/165703129-3daa36f8-cb3a-4311-b15b-80bb5f02a9b4.png">

**Comment by thomasdarimont** [comment]
@xianli123 that looks nice! Wasn't there also a "copy to clip-board" action? I think that would be useful too :)

**Comment by xianli123** [comment]
@thomasdarimont It looks like the screenshot below. The visible icon is in front of the copy icon. WDYT?
<img width="812" alt="Screen Shot 2022-04-28 at 16 24 50" src="https://user-images.githubusercontent.com/53931519/165710419-47785dbb-168c-483b-89c0-d8a764edb381.png">
