### ISSUE TITLE
Add support to search or filter mappers by name when creating client-scopes

### ISSUE THREAD

**Issue by thomasdarimont** [keycloak/keycloak-admin-ui#2513]
### Description

Realm configurations with many custom mappers require scrolling to find the proper mapper by name when configuring a client scope.

**Comment by edewit** [comment]
I'm not sure what you mean by this @thomasdarimont we have a much better search / filter option atm
![image](https://user-images.githubusercontent.com/51133/165706909-e9e70bc2-dffe-4fd0-964e-04ab80e61140.png)

**Comment by thomasdarimont** [comment]
Sorry I meant a different thing -> Assigning Mappers within a client scope (I'm going to reword the issue to make this more clear)

![image](https://user-images.githubusercontent.com/314690/165708030-0b3b7a04-688f-463c-a097-6bb67d73dce9.png)
