### ISSUE TITLE
X-Frame-Options url not found

### ISSUE THREAD

**Issue by zakariae-lebriq** [keycloak/keycloak-admin-ui#2534]
### Describe the bug

The page http://tools.ietf.org/html/rfc7034 is not found when you click on X-Frame-Options in the security defenses ( realm config) to get more information

### Version

15.1.1

### Expected behavior

Display more information about X-Frame-Options

### Actual behavior

404 page not found

### How to Reproduce?

Juste click on X-Frame-Options in the realm settings ( security defenses )

**Comment by ssilvert** [comment]
Thanks for reporting this @zakariae-lebriq.

We won't be working on smaller fixes to the old UI, but the same problem exists in the new admin UI, so I have moved the issue to the corresponding repository.

**Comment by ssilvert** [comment]
Since this is such a simple fix, I went ahead and added it to Milestone 19.

**Comment by edewit** [comment]
for me both of those links work

**Comment by ssilvert** [comment]
@edewit I see the problem now.  For me it looks fixed as well, but when I looked at it before I was getting 404 like @zakariae-lebriq reported.

If you put http://tools.ietf.org/html/rfc7034 into your browser it will return a 301 Moved Permanently error.  It will then redirect to https and ultimately, to the datatracker.ietf.org URL.  I guess sometimes the 301 doesn't happen and you get a 404 instead.

I think that all we need to do is change from http to https.

**Comment by jonkoops** [comment]
@ssilvert I've created #2558 to update all the links in the application so they end up where they redirect. Can you take a look?
