### ISSUE TITLE
[UX Review] The Test button doesn't work in the LDAP user federation

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-admin-ui#2581]
### Describe the bug

In the LDAP user federation, the "Test connection" button and the "Test Authentication" don't work during the creation process, even if all the required settings are set up.

<img width="767" alt="Screen Shot 2022-05-07 at 10 44 15" src="https://user-images.githubusercontent.com/53931519/167234939-77cdc831-77ea-49e4-ac51-b910b6b190f2.png">

### Version

Admin new UI

**Comment by ssilvert** [comment]
@xianli123 I got the connection working.  What problem do you see?

<img width="806" alt="LDAP-connection" src="https://user-images.githubusercontent.com/507202/167404914-5dd62ce7-a3e7-422e-b810-91375cd58634.png">

**Comment by xianli123** [comment]
I try it again. It works for now. I will close this issue. Thanks!
