### ISSUE TITLE
Status of project

### ISSUE THREAD

**Issue by xesjkeee** [keycloak/keycloak-admin-ui#262]
Hey, team 👋
Thanks for all your improve to be Keycloak is much better!

I just want to make my own enterprise theme for my company, but some pages of **keycloak-admin-ui** are not ready.
Maybe you have roadmap or prediction when components/pages of admin-ui v2 will be ready?

**Comment by edewit** [comment]
yes it's still early days for the project can't make promises when we'll be done, but you are welcome to help. Styling will be available by adding patternfly overrides see: https://www.patternfly.org/v4/developer-resources/global-css-variables
