### ISSUE TITLE
Unable to open row items details in table 

### ISSUE THREAD

**Issue by ikhomyn** [keycloak/keycloak-admin-ui#2630]
### Describe the bug

Having a single log item without expand button in the table, following items with expand button,  unable to open details 

### Version

Keycloak 999-SNAPSHOT on JVM (powered by Quarkus 2.7.5.Final

### Expected behavior

Should allow to open row item details by clicking on row item expand button.

### Actual behavior

Not working if table contains a single item without expand button. Only followed items are affected.

### How to Reproduce?

1. Generate any event without user details
2. Go to Events -> User events
3. Click expand button on any following item after the item without information.

![Screenshot from 2022-05-12 18-00-39](https://user-images.githubusercontent.com/89014675/168118770-9b582d46-8be8-47b3-893b-89fcb38de104.png)

**Comment by edewit** [comment]
@ikhomyn how do I get an item without an expand button? From your screenshot I need a logout_error, how do I do that?

**Comment by ikhomyn** [comment]
@edewit, I just Sign out
![Screenshot from 2022-05-13 11-08-42](https://user-images.githubusercontent.com/89014675/168251162-4fa1569d-f60e-48c3-a321-645f5e9f30ca.png)

![Screenshot from 2022-05-13 11-09-14](https://user-images.githubusercontent.com/89014675/168251213-1fe8721e-95bf-406a-acf4-a15081f39e21.png)

**Comment by edewit** [comment]
This error means you are testing against an older version of keycloak

**Comment by jonkoops** [comment]
Yeah, this issue should be resolved in newer versions. I'd recommend to use the Nightly dev server to test against, see the [documentation](https://github.com/keycloak/keycloak-admin-ui#running-the-keycloak-server).
