### ISSUE TITLE
"ACR to LoA Mapping" field missing from realm settings > login tab

### ISSUE THREAD

**Issue by agagancarczyk** [keycloak/keycloak-admin-ui#2668]
### Description

In the old Admin Console, the Realm Settings > Login tab has "ACR to LoA Mapping" field. This field is not present in the new Admin Console. It's suspected that this may be a new setting. It is related to the Level of Authentication.

![Screenshot 2022-05-17 at 14 44 50](https://user-images.githubusercontent.com/4890675/169012667-48bc72c3-cad4-4364-ae57-81b585f03914.png)

**Comment by agagancarczyk** [comment]
hi @ssilvert should we set it to milestone 19 or 20?

**Comment by ssilvert** [comment]
@agagancarczyk This should be fixed: https://github.com/keycloak/keycloak-admin-ui/issues/2187

Can you verify and close this if it looks good?

**Comment by jonkoops** [comment]
This has been implemented for the client setting (see the 'Advanced' tab of a client) but it has not been implemented under the realm settings.

@ssilvert should this functionality also be implemented at the realm settings level?
