### ISSUE TITLE
[UX Review] Add "Log out all sessions" in the user Sessions tab

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-admin-ui#2673]
### Describe the bug

The "Log out all sessions" button is missing in the user Sessions tab. It can be added as shown in the screenshot below.

<img width="1147" alt="Screen Shot 2022-05-23 at 11 29 13" src="https://user-images.githubusercontent.com/53931519/169738060-7afa1bb2-45ce-4383-85e3-1104265f7e2c.png">

### Version

Admin new UI

**Comment by jonkoops** [comment]
@xianli123 this is already present in the 'Action' menu above I believe.

**Comment by xianli123** [comment]
Sorry, but I didn't see the "Log out all sessions" in the Action menu. And I think this button should be put in the user sessions table. What do you think?
Certainly, it is good to put "Log out all sessions" in the Action menu of the Sessions tab(left nav bar).
