### ISSUE TITLE
Update translations before Milestone 19

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-admin-ui#2743]
### Description

We are still getting community contributions for i18n in the old admin console.  After Milestone 19, I plan to stop accepting those contributions.

But just before Milestone 19 hits, we should probably pull translations from the old UI one last time.  I know of a couple of pending PR's for translations and there may have been others.

https://github.com/keycloak/keycloak/pull/11950
https://github.com/keycloak/keycloak/pull/12054

**Comment by edewit** [comment]
https://github.com/keycloak/keycloak/pull/12054 is for account or email... so not relevant for us

**Comment by ssilvert** [comment]
> [keycloak/keycloak#12054](https://github.com/keycloak/keycloak/pull/12054) is for account or email... so not relevant for us

Yes, you are right.  

So I take it your PR #2786 ran against all the admin translations in keycloak/keycloak and it only came up with one new one?

If that means we are done then I will stop accepting new translations for admin in the keycloak/keycloak repo.  Just let me know.

**Comment by edewit** [comment]
That is right
