### ISSUE TITLE
Create bearer-only clients via Admin UI

### ISSUE THREAD

**Issue by danielFesenmeyer** [keycloak/keycloak-admin-ui#2770]
### Description

I did not find a way to create a bearer-only client via the new Admin UI.

The new Admin UI recognizes existing bearer-only clients (clients I have created with the old Admin UI) - it shows the tooltip: "This is a special OIDC type. This client only allows bearer token requests and cannot participate in browser logins."

But how can I create such bearer-only clients? I created a client without any flows enabled, but the resulting client was not recognized as "bearer-only": there is no tooltip and I did also not find a way to convert the client to "bearer-only".

This is the "Capability config" I used to create the client:
![adminUIV2ClientCreation](https://user-images.githubusercontent.com/11198630/172436169-daf09ab1-6d58-41f3-83ee-fc4ef2ca2f26.PNG)

Maybe I just overlooked something?

### Motivation

Our customers use bearer-only clients quite often and some of them use the Admin UI to create such clients. Therefore, it would be very helpful if the new Admin UI would support that functionality.

### Details

I used the version distributed as preview feature of Keycloak 18.0.0.

**Comment by edewit** [comment]
The creation of bearer only clients has been deprecated and therefor is no longer supported in the new UI

**Comment by danielFesenmeyer** [comment]
Good to know. Did not know about that. Is there some migration guide on this issue, I mean how to create "bearer-only"-like clients with the new UI? Are those just public clients without any flows?

**Comment by xianli123** [comment]
Hi @danielFesenmeyer In the new UI, users will not be able to create the bearer-only client. Because 'Bearer-only' clients are web services that never initiate a login. We get rid of the type.

**Comment by jonkoops** [comment]
Closing this issue as we do not intent to implement this feature. I think that @danielFesenmeyer's point on having some migration documented would be nice, do we have this anywhere?
