### ISSUE TITLE
Navigation links cannot be opened in new tab

### ISSUE THREAD

**Issue by danielFesenmeyer** [keycloak/keycloak-admin-ui#2777]
### Describe the bug

The links in the left-side navigation of the Admin UI are not correct. E.g. when trying to open "Clients" in a new tab, I get an error "404 Not Found".

### Version

18.0.0

### Expected behavior

When opening the "Clients" link in a new tab, the clients of the currently selected realm should be displayed in this tab.

### Actual behavior

When opening the "Clients" link in a new tab, I get an error "404 Not Found".

### How to Reproduce?

1. Start Keycloak.X with the following command:

```
./kc.sh start-dev --features=preview
```

2. Open the Admin UI, for example by opening the URL http://localhost:8080/admin/master/console/#/

3. Open the "Clients" link (from the left-side navigation) in a new tab.
4. The new tab shows an error "404 Not Found".

### Anything else?

This issue seems to affect all links of the left-side navigation, not only the "Clients" link.

Screenshot showing the incorrect "Clients" link (see "localhost:8080/master/clients" in the left bottom corner):
![adminUIV2NavigationLinks](https://user-images.githubusercontent.com/11198630/172647996-8da1156d-87e9-483c-9077-cc58ade7d1c0.PNG)

**Comment by ssilvert** [comment]
Thanks for reporting this @danielFesenmeyer.
