### ISSUE TITLE
Client scopes > Mappers > "Configure a new mapper" dialog has possibly incorrect heading

### ISSUE THREAD

**Issue by agagancarczyk** [keycloak/keycloak-admin-ui#2810]
### Describe the bug

Clicking "Configure a new mapper" displays a dialog with the same heading as the dialog opened using "Add predefined mapper".

The following are the two dialogs with the same headings:

![Screenshot 2022-06-14 at 17 10 04](https://user-images.githubusercontent.com/4890675/173626028-e25aaa38-0221-453a-b7a8-c839962cfa15.png)
![Screenshot 2022-06-14 at 17 10 12](https://user-images.githubusercontent.com/4890675/173626035-7983b6aa-1c7f-4cfb-a6ea-7a2c4af3bf51.png)

The suggested change is to change the heading "Add predefined mappers" in the dialog opened via clicking "Configure a new mapper" to "Configure a new mapper". 

@xianli123 could you please review and let me know if this is something we would like to fix? Thanks

### Version

17.0.0

**Comment by agagancarczyk** [comment]
Thanks @xianli123 - I'll fix it

**Comment by xianli123** [comment]
@agagancarczyk Thanks!

**Comment by agagancarczyk** [comment]
hi @xianli123 I have just fixed the heading, but I'm now thinking about changing the subheading for the "Configure a new mapper" dialog as well, which is the same as the subheading for the "Add predefined mapper" dialog. 

Do you think we could change the subheading in the "Configure a new mapper" dialog to "Choose any of the mappings from this table"? instead of "Choose any of the predefined mappings from this table"? The word "predefined" is a b it confusing here as we are essentially creating a new mapper here. Wdyt? Thanks

**Comment by agagancarczyk** [comment]
Completed.
