### ISSUE TITLE
View client > Client scopes > Setup > Removing client scope from the list is not showing a standard Delete dialog

### ISSUE THREAD

**Issue by agagancarczyk** [keycloak/keycloak-admin-ui#2811]
### Describe the bug

Removing client scope from the list is not showing our standard Delete dialog. 

Steps to replicate: 
1. Go to the "Clients" side menu item and select a previously created client from the list - in my case it's "Target-client"
![Screenshot 2022-06-16 at 16 02 36](https://user-images.githubusercontent.com/4890675/174100329-ef76c118-2ac6-459d-a37a-a9c4905956f8.png)

2. Go to the "Client scopes" tab of that selected client and try to "Remove" any client scope 
![Screenshot 2022-06-16 at 16 06 58](https://user-images.githubusercontent.com/4890675/174101251-ff0ef2b8-045a-437b-9c62-57e10dc1f5b5.png)

4. Observe that the dialog for deleting/removing doesn't display

@xianli123 could you please review if this is the intended behavior or would we like to add the dialog for the user to confirm that he/she wants to remove the client scope. Thanks

### Version

17.0.0

**Comment by xianli123** [comment]
I found there is a confirmation dialog. But I am not sure if this is the page you mentioned. Could you please share a screenshot of the list with me?

<img width="901" alt="Screen Shot 2022-06-16 at 15 49 27" src="https://user-images.githubusercontent.com/53931519/174020106-e16a9ca1-009b-4d16-87e8-5797a8f7b5ab.png">

**Comment by agagancarczyk** [comment]
Thanks @xianli123 I have now added steps with screenshots.

**Comment by xianli123** [comment]
Hi @agagancarczyk Thanks and sorry for misunderstanding your concerns. We can add a dialog as shown below if users want to remove a specific client scope. The "Remove" button is in blue color because it is not a dangerous action. WDYT?

<img width="793" alt="Screen Shot 2022-06-17 at 00 08 03" src="https://user-images.githubusercontent.com/53931519/174116194-59c575af-ea51-4884-b3bb-26b5c12d3e13.png">

**Comment by agagancarczyk** [comment]
Thanks @xianli123 yes, sure, your proposal looks good to me - thanks again

**Comment by xianli123** [comment]
Thanks
