### ISSUE TITLE
Create profile/policy: Headings consistency

### ISSUE THREAD

**Issue by agagancarczyk** [keycloak/keycloak-admin-ui#2817]
### Describe the bug

hi @xianli123 I have noticed that there is a small discrepancy between headings in two forms.

1. Create a client policy (Realm settings > Client policies tab > Policies subtab > Click "Create client policy" button: )
![Screenshot 2022-06-17 at 11 37 15](https://user-images.githubusercontent.com/4890675/174282886-d26dce7d-c04d-4538-8229-9ef6ff59cfc8.png)

3. Create a client profile (Realm settings > Client policies tab > Click "Create client profile" button: )
![Screenshot 2022-06-17 at 11 37 06](https://user-images.githubusercontent.com/4890675/174282846-1c7d3a91-8959-43c1-8e6b-144693a06251.png)

My suggestion is to change the heading in the policy form from "Create policy" to "Create client policy" to keep it consistent with the heading in the other form. Wdyt? Thanks

### Version

17.0.0

**Comment by xianli123** [comment]
Hi @agagancarczyk I agree with you. Thanks for your good idea.
