### ISSUE TITLE
Realm settings > Partial export dialog accessed from Action dropdown

### ISSUE THREAD

**Issue by agagancarczyk** [keycloak/keycloak-admin-ui#2818]
### Describe the bug

The subheading is missing in this dialog. Please see the screenshot.

![Screenshot 2022-06-17 at 13 40 17](https://user-images.githubusercontent.com/4890675/174300564-103d3b2b-1bc1-4a52-a85a-a3926d54f25a.png)

@xianli123 could you please advise on the subheading text I could add to this dialog? Thanks

### Version

17.0.0

**Comment by xianli123** [comment]
Hi @agagancarczyk With regard to the subheading text, we can refer to the design below. Thanks!

<img width="419" alt="Screen Shot 2022-06-20 at 09 30 57" src="https://user-images.githubusercontent.com/53931519/174510107-d37dfa07-8cc2-4388-b581-f53e12e3e81d.png">
