### ISSUE TITLE
Error: After changing realm name in realm settings account-console client base url not changing

### ISSUE THREAD

**Issue by vlkndogan** [keycloak/keycloak-admin-ui#287]
1. Go to your realm settings 
2. change the name of realm 
3. Now go to client in that realm
4. Base url of account,security-admin-console these clients changing url of the account console not changing.

**Comment by jonkoops** [comment]
It's no longer possible to edit the id of the realm, although this is possible in the old admin console. @ssilvert what do we want to do here?

**Comment by ssilvert** [comment]
I think we need to wait before we re-enable the "rename realm" function.  I'd like to see how this is resolved first: https://issues.redhat.com/browse/KEYCLOAK-18601

**Comment by jonkoops** [comment]
Since this is a bug in the old admin console I am closing this. I've created a new issue to implement this functionality here https://github.com/keycloak/keycloak-admin-ui/issues/941
