### ISSUE TITLE
realm roles(attributes): set key fields to read-only after save

### ISSUE THREAD

**Issue by jenny-s51** [keycloak/keycloak-admin-ui#291]
follows #264 

set key input fields to read-only on `save()` form submission

**Comment by edewit** [comment]
In the old console this was done because it was the easiest way to implement it, I guess. But the keycloak API has no problem with changing keys of existing attributes, so why would we make them readonly after a `save`? Wouldn't it be better / more user friendly to allow the user to change keys?

**Comment by jenny-s51** [comment]
@edewit I definitely agree. 

@yih-wang what are your thoughts?

**Comment by yih-wang** [comment]
@jenny-s51 @edewit Yes that sounds great. Make the keys editable is more friendly.

**Comment by jenny-s51** [comment]
Closing this based on feedback from @edewit and @yih-wang - consensus that editable keys are more user-friendly
