### ISSUE TITLE
[UX Review] Remove the redundant part in the Role details page

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-admin-ui#2949]
### Describe the bug

As shown in the screenshot below, the "Create role" part on the Role details page is redundant. The same issue happens to the Client Roles. we can remove it. Thanks!

<img width="1440" alt="Screen Shot 2022-07-11 at 14 18 29" src="https://user-images.githubusercontent.com/53931519/178212851-f487604d-250c-4ed3-bf47-8b157d7a9a4b.png">

### Version

Admin new UI

**Comment by dominikkawka** [comment]
Hey @xianli123 , I've given it a quick look at it seems to be fixed? 
![image](https://user-images.githubusercontent.com/31955648/181521290-ee756186-995c-4db8-a976-98d85906dfd5.png)
![image](https://user-images.githubusercontent.com/31955648/181521827-9572e8ae-7946-4bc0-9884-02fa2df84a77.png)
