### ISSUE TITLE
Removal of English language not possible

### ISSUE THREAD

**Issue by psytester** [keycloak/keycloak-admin-ui#2953]
### Describe the bug

I have a Realm with configured localization.
List of supported locales: English & Deutsch
Default locale: Deutsch

I want to remove English from list of supported locales, but this is not possible.
As counterpart, I'm able to remove Deutsch.

I'm using Quarkus KC 18.0.2 with new Admin UI

Notice: In old Admin UI the removal of Englisch is possible

### Version

18.0.2

### How to Reproduce?

Add two locales, one is English and save
Now remove English again

**Comment by xianli123** [comment]
Sorry for the late reply. English is the default language of the system, users should not be allowed to remove English.

**Comment by psytester** [comment]
In my opinion, this is a regression.
And there may be projects with localization enabled, but let's assume that only non-English is used, e.g. in Belgium with Dutch, French and German.

**Comment by jonkoops** [comment]
I have to agree that if there is a single language configured that should be enough. It should just never be the case that no language is configured.

**Comment by xianli123** [comment]
I'm not sure if the language is configured through the UI or backend. Maybe we should involve @stianst @ssilvert  in our discussion. Hi @stianst  @ssilvert, what do you think? Thanks!

**Comment by edewit** [comment]
Well @xianli123 it did work like this in the old console, that you can't remove English is only enforced in the new UI

**Comment by ssilvert** [comment]
Not having English as a choice for end users is definitely a valid use case.  We will need to fix this one way or another.
