### ISSUE TITLE
New admin UI : no support for array in custom attributes

### ISSUE THREAD

**Issue by christopheblin** [keycloak/keycloak-admin-ui#2988]
### Describe the bug

In previous version of the admin console, when an attribute is an array, the UI displays values separated by ##

In the new version, 
* if I use "##" it creates a single value with "##" inside 
* if I add a second attribute with the same key, it keeps only the second value

-> in the new version, there is no support for array in custom attributes

### Version

18

### Expected behavior

Adding a second key with the same name of another key should create an array (or we should be able to have a "+" button to add multiple values to a key

**Comment by jonkoops** [comment]
This is indeed something that is currently missing, not sure if we should keep this functionality the same as in the old UI as that seems like quite a cryptic process.

@xianli123 could you take a look at this feature and see if it's UX is up to snuff? Perhaps there is a better way to implement this.

**Comment by jonkoops** [comment]
Since this is missing functionality I am marking this as a critical issue that ideally should be included in the next patch release.

**Comment by xianli123** [comment]
Hi @jonkoops @christopheblin Do you mean the multiple value components, as shown in the screenshot below? Could you please share a screenshot of the issue you mentioned? Thanks!
<img width="1122" alt="Screen Shot 2022-08-01 at 19 00 52" src="https://user-images.githubusercontent.com/53931519/182134244-f6c1b0f1-1e8c-470b-a102-84e8aaaf729c.png">
