### ISSUE TITLE
Identity Provider Mapper can not save name of Hardcoded Attribute

### ISSUE THREAD

**Issue by lexcao** [keycloak/keycloak-admin-ui#3022]
### Describe the bug

As title descried and created from https://github.com/keycloak/keycloak/issues/13374

### Version

19.0.1

### Expected behavior

The name of the Hardcoded Attribute should be saved in Identity Provider Mapper.

### Actual behavior

Not saved.

### How to Reproduce?

1. Use the 19.0.0 Keycloak or Keycloak admin UI
2. Go to `Identity Providers`
3. Create a demo provider
4. Go to `Mappers` tab
5. Create a mapper
6. Choose `Hardcoded Attribute`
7. Input some test data
8. Click `save`

### Anything else?

I have some Investigations on my local keycloak.
It may be an expected behavior with `react-hook-form`, we need to adapt for new admin UI.

First, the hardcoded attribute mapper has the below properties
```
config.attribute  // for the name of Hardcoded User Attribute
config.attribute.value // for the value of Hardcoded User Attribute
```

Then, when passing these fields to `react-hook-form`, like this
```
register('attribute');
register('attribute.value');
```

While submitting, it builds a form object for the event, like this
```
{
 "attribute": { "value": "some-value" }
}
```
The `config.attribute` is removed from the form request, so the data is not saved correctly.

**Comment by lexcao** [comment]
I found this issue also impacts other JSON config post requests. 

https://github.com/keycloak/keycloak/issues/13416

Which registers the `react-hook-form` field of this
```
register('x509-cert-auth.mapping-source-selection');
register('x509-cert-auth.xxxx');
```
Then builds the form object like this
```
"config": {
  "x509-cert-auth": {
    "mapping-source-selection": "xx",
    ...
}
```

**Comment by lexcao** [comment]
I have found these 4 util functions, which can help fix the issue.
(There is a draft PR I am going to demo the fixing, #3023)

for react-hook-form
- `convertFormValuesToObject`
- `convertToFormValues`

for MultivaluedString
- `stringToMultiline`
- `toStringValue`

I am willing to fix the issue, but I need come confirmation about the way to fix it.

---
Firstly, for react-hook-form, I have googled the method about converting key of form object but found nothing.
There might be required to call the two util functions in somewhere of `save` and `setupForm` methods.
If so, there might be missing handling of the config fields like this issue in the future, then we need to add the conversion manually.

Then, for MultivaluedString, I found there is `MultivaluedStringComponent.tsx` uses the `MultiLineInput` component that handles the multi-value as a list, which causes the caller needs to make a conversion manually.

The draft PR is modified in the way I described above.

But, I want to check with the team. Is there possible for the MultivaluedStringComponent just handles the multivalued string as the string like before? This may need changes for the component.

And, I am willing to write some tests to cover these cases, could you please guide me on how?

Regards.

**Comment by edewit** [comment]
The problem is that react hook form will convert something something like this:
```js
config: {
   "attribute.value": "some-value"
}
```
into:
```js
config: {
   attribute: {
      value: "some-value"
   }
}
```
We already have convert functions that handle this and other problems (like multi line inputs)

In this case though these do not work, because there is another config value named `attribute` so the conversion will overwrite the `attribute.value`:

```js
{
   config: { 
      attribute: "attr",
      "attribute.value": "some-value"
   }
}
```
if we want to convert this to an object for react-hook-form we get only `attribute` = "attr", because attrubute can't be an object and a string at the same time. e.g.

```js
{
   config: {
      attribute: "attr",
      attribute: { value: "some-value" },
   }
}
```

**Comment by cfBrianMiller** [comment]
@jonkoops When will a release deployed that includes the changes made in #3035 ?

**Comment by jonkoops** [comment]
We're expecting a patch release in the next couple of weeks.

**Comment by mortenjoenby** [comment]
Hi.
This is a critical issue to us as we are supporting several hundred realms across several Keycloak cluster, which we have just upgraded to 19.0.1 ...!
When can we expect 19.0.2 to be released - assuming this will contain the fix?
Is it an option to run with the old Admin Console until then?

Thanks,
Morten

**Comment by ssilvert** [comment]
> Hi. This is a critical issue to us as we are supporting several hundred realms across several Keycloak cluster, which we have just upgraded to 19.0.1 ...! When can we expect 19.0.2 to be released - assuming this will contain the fix? Is it an option to run with the old Admin Console until then?
> 
> Thanks, Morten

I am expecting 19.0.2 very soon.  Hopefully before the end of the week.

Note that you can revert to the old console.
1. Go to Ream settings --> Themes
2. Select "keycloak" for Admin console theme.
3. Refresh your browser

**Comment by mortenjoenby** [comment]
Thanks @ssilvert !
Much appreciated. We will use the old theme until we have patched 19.0.2.
We are also awaiting that to fix the issue with /health/live endpoint making our pods die when setting http-relative-path.

**Comment by fuomag9** [comment]
> > Hi. This is a critical issue to us as we are supporting several hundred realms across several Keycloak cluster, which we have just upgraded to 19.0.1 ...! When can we expect 19.0.2 to be released - assuming this will contain the fix? Is it an option to run with the old Admin Console until then?
> > Thanks, Morten
> 
> I am expecting 19.0.2 very soon. Hopefully before the end of the week.
> 
> Note that you can revert to the old console.
> 
> 1. Go to Ream settings --> Themes
> 2. Select "keycloak" for Admin console theme.
> 3. Refresh your browser

Not fixed in 19.0.2

**Comment by fuomag9** [comment]
> @fuomag9 what do you mean not fixed? I just tried it and it works just fine
When trying to click on the wheel to edit the recaptcha
![image](https://user-images.githubusercontent.com/1580624/191036682-abac568a-9daf-4989-a465-a26d63635535.png)

**Comment by edewit** [comment]
this issue is about `Hardcoded Attribute` on the Identity Provider could you create a new issue for this specific one?
