### ISSUE TITLE
 Unable to Import Client with SAML XML Metadata

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak-admin-ui#3041]
### Describe the bug

Quoting [original post](https://keycloak.discourse.group/t/unable-to-import-client-with-saml-xml-metadata-19-0/16715/1):

> In previous versions, such as 16.x, when you create a Client, you could import a SAML Metadata, which is in XML format. We have not moved to 19.x and that is no longer available. It looks like you can only upload it if it is in JSON format. Is there a reason being able to upload a XML SAML Metadata is removed? Or is there a converter that can easily be used? Almost every application I have come across gives you an XML file for the metadata. Please advise.

This is a regression from legacy admin UI

### Version

19.0.1

### Expected behavior

Import new client works with SAML XML descriptors

### Actual behavior

SAML XML descriptors are not parsed

### How to Reproduce?

1. Go to Import client page
2. Upload https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/base/src/test/resources/client-descriptions/saml-entity-descriptor.xml

### Anything else?

This feature works in legacy admin console in Keycloak 19.0.1

**Comment by ssilvert** [comment]
This should be relatively easy for us to implement.  There is a "client-description-converter" endpoint that processes the XML on the back end.  So it should be easy to do the same way the old console does it.

**Comment by edewit** [comment]
This functionality is still there you just need to throw the switch (use entity descriptor) to use the upload instead as the flow of this is a bit different now:
![image](https://user-images.githubusercontent.com/51133/182776077-1f5f8411-d7c8-4a4f-83b4-3745013dbfb9.png)

**Comment by hmlnarik** [comment]
@edewit The user wants to configure a client based on descriptor regardless of it being SAML or OIDC. When it was possible to do it in the previous admin console, why has a different, more complex approach, been taken in the new admin UI?

Per the original request, it leads to the confusion indicating that this functionality has been removed completely. This translates to a very bad user experience.

Please implement.

**Comment by jonkoops** [comment]
@cesdperez could you log a separate issue for this? It helps us keep track of these kind of issues.

**Comment by edewit** [comment]
@cesdperez I can not reproduce this would it be possible for you to attach the file that you used to test this with?

**Comment by sinannoureddine** [comment]
will this UI fix be updated in the distribution from the website? I tried downloading Keycloak from the website and it has the same issue

**Comment by edewit** [comment]
@sinannoureddine yes, in the 19.0.2 release, but it's not released yet. You can change to the old ui as a workaround for now.
