### ISSUE TITLE
Identity provider "Sync Mode" not visible

### ISSUE THREAD

**Issue by danielFesenmeyer** [keycloak/keycloak-admin-ui#3082]
### Describe the bug

I tried to configure "Sync Mode" `force` for an Identity Provider. In the old admin UI, there was a combobox, where I could select one of the different modes (`force`, in my case).
In the new Admin UI, that combobox is hidden by the "save/revert" overlay and I can not access it (without dev tools).

### Version

19.0.1

### Expected behavior

The "Sync Mode" combobox should be easily accessible.

### Actual behavior

The "Sync Mode" combobox is not accessible, because it is hidden by the "save/revert" overlay.

### How to Reproduce?

I guess it happens when selecting an arbitrary Identity Provider - I used one of type keycloak-oidc.

### Anything else?

Browser: Google Chrome, Version102.0.5005.61 (Official Build) (64-bit)

Screenshot:
![idpSyncModeHidden](https://user-images.githubusercontent.com/11198630/183602258-748e7792-a2f3-4b57-ac92-e9f23cd7168c.PNG)

**Comment by ssilvert** [comment]
I'm on Chrome version Version 103.0.5060.134 (Official Build) (64-bit) and Sync Mode works fine.  It also seems to work ok on FireFox.

The dropdown appears above the field rather than below.  (The dropdown actually "drops up")

Can you try on a different browser to see what happens?

**Comment by danielFesenmeyer** [comment]
Checked it also on Firefox (103.0 (64-bit)) and with newer Chrome Version (Version 104.0.5112.79 (Official Build) (64-bit)).
In all cases the dropdown is hidden by the "save/revert"-overlay.

Btw, I'm using Ubuntu 20.04.2 LTS. And my screen resolution is 1920 x 1080.

**Comment by edewit** [comment]
fixed by https://github.com/keycloak/keycloak-admin-ui/pull/3053

**Comment by danielFesenmeyer** [comment]
Thanks for the info :)

**Comment by sharpedavid** [comment]
@edewit Can you guess why "Sync Mode" and "Use PKCE" options would be unavailable on the UI in Keycloak 18.0.2 legacy? I am seeing weird behaviour where a fresh, standalone, laptop install of Keycloak shows these IDP configuration options, but my production, managed server install of Keycloak does now show these fields. Is it possible that these fields can be lost based on configuration differences?
