### ISSUE TITLE
[UX review] Dashboard reviews and fine-tuning

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-admin-ui#341]
Hi @edewit 
I reviewed the new console UI and listed some updates of Dashboard here. You can find the corresponding points in the screen below.
1. The space between Version and 12.0.2 should be 8px. And the space between 12.0.2 should be 16px. The first letter of “community” is capitalized.
2. The space between these two tiles should be 24px.
3. We need to add a question mark after "Enabled features" and "Disabled features" separately to explain what “Enabled features" and "Disabled features" mean.
4. Some "Enabled features" have a label named Preview or Experimental. Maybe we can display the label for some Enabled features.
5. I've ignored responsive design at first. In order to fit the different screen sizes, I uploaded the [responsive design](https://marvelapp.com/prototype/baei9db/screen/76402175) to Marvel, please check it.

![Dashboard](https://user-images.githubusercontent.com/53931519/106242957-7a5a4800-6243-11eb-88e0-8b6ff10d26c0.png)

**Comment by edewit** [comment]
The labels are there if the feature is "preview" or "experimental" when I enable scripts I get:
![image](https://user-images.githubusercontent.com/51133/106248249-03a45700-6211-11eb-8cf9-8e637aca1111.png)

**Comment by xianli123** [comment]
OK, I see. I think we can use different labels to distinguish "Preview" and "Experimental". E.g. we can use the blue labels to indicate ”Preview“ and the yellow label to indicate "Experimental". WDYT?

**Comment by edewit** [comment]
Right, I have gray for preview can change this to blue, there is no "yellow" I have used "orange" for Experimental (also there are no Experimental features atm (keycloak 12))

**Comment by edewit** [comment]
I'm using this [patternfly component](https://www.patternfly.org/v4/components/description-list) to create the descriptions

**Comment by ssilvert** [comment]
@xianli123 @edewit I have a feeling that this will not be the final design.  Let's wait until we get some feedback from the Electron release before we put any more effort into it.

**Comment by xianli123** [comment]
OK, once we have the final decision, I will update the design wireframe.
