### ISSUE TITLE
General layouts - add empty state to storybook

### ISSUE THREAD

**Issue by srambach** [keycloak/keycloak-admin-ui#35]
https://marvelapp.com/prototype/504f2fh/screen/72066305

**Comment by yordis** [comment]
@srambach is there any place I could see all the work done in Marvel?

I would love to closely follow this project 🙏

**Comment by ssilvert** [comment]
> @srambach is there any place I could see all the work done in Marvel?
> 
> I would love to closely follow this project 🙏

@yordis Here is the link: https://marvelapp.com/folder/d1tTZOiQig

Feedback is much appreciated.
