### ISSUE TITLE
[UX review] Client list screens

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-admin-ui#352]
Hi, @edewit I've reviewed the Client list page, there are some updates about this part.

First of all, there are two tabs namely "Client list" and "Initial access token" in the latest design. The "Client list" looks like what we have designed before. The "Initial access token" is moved to the **Client page** from "**Realm settings**". Please check the marvel link to dig into the details.
- Client list design: https://marvelapp.com/prototype/f00e9jb/screen/71968754
- Initial access token design: https://marvelapp.com/prototype/fcf2450/screen/74745145

After that, there are some details that need to be updated, as shown in the screenshot below.
1.  It will be good to add the dividing lines.   
2. The space between the **Client ID** and the label should be 8 px.   
3. It would be better to display the whole name. 
4. The link and title are aligned to the left. The font size of the link is different from the other words in the table. The space between the link words and the icon should be 8 px.  
5. In the new design, users can't delete the built-in client provided by Keycloak. Therefore, the **Delete** option in the built-in client is disabled.   
6. The table should fill the entire white page. There is no gap.  

Current implementation:
![ClientList](https://user-images.githubusercontent.com/53931519/106708263-84a68880-662d-11eb-849d-a94df9198d30.png)

Specs:
![ClientList_1](https://user-images.githubusercontent.com/53931519/106708301-9720c200-662d-11eb-9a99-53aaf9bcd96b.png)

Thanks.

**Comment by edewit** [comment]
@xianli123 there is currently no way to know if a client is a build in client.

**Comment by xianli123** [comment]
In the old console, if users created a new realm, they would find that there were some built-in clients. These clients shouldn't be deleted in the new design.
<img width="1193" alt="Screen Shot 2021-02-09 at 11 36 55 AM" src="https://user-images.githubusercontent.com/53931519/107312627-ce7aed00-6acb-11eb-9670-9f5ff7f488eb.png">

**Comment by edewit** [comment]
right, I get what you mean, but there is no api to determine if a client is
a build in one.

**Comment by xianli123** [comment]
Yes. Do you know who can help us to provide the API?

**Comment by ssilvert** [comment]
@xianli123 Did we discuss which clients should not be deleted?  I think there are use cases for removing at least some of them.

Though you could make the argument that disabling serves the same purpose, I'm not sure all customers would agree.

I'm thinking that if we did agree to restrict removal of certain clients then maybe it is ok to hard-code that logic for now.  @xianli123 if you can point at what we agreed to then we can take that to Stian and asks what he thinks about hard-coding it.

**Comment by xianli123** [comment]
@ssilvert I remember we have discussed this part. In the new design, the default clients shouldn't be deleted, and the client that is created or imported by the user can be deleted. We can confirm this part with Stian, and then decide what we should do later. WDYT?

**Comment by yih-wang** [comment]
@edewit An additional comment to the toolbar layout - the buttons are supposed to have some space between each other. It seems that they're close to each other right now.

**Comment by yih-wang** [comment]
An additional additional comment is I just found this is no way to return to the original list after any filter applies. @xianli123 Do we have any design guidelines for that?

**Comment by xianli123** [comment]
Hi @Erik, there are some details that need to be fine-tuned as shown in the picture below.

A. The distance between the top nav bar and the left menu bar should be 24 px.
B. The pagination can display more information. We can reference [the pagination component](https://www.patternfly.org/v4/components/pagination#top) of PF4.

![8](https://user-images.githubusercontent.com/53931519/111267892-8e2d0280-8667-11eb-9d7f-30aa8786a105.png)

**Comment by edewit** [comment]
@xianli123 
> The pagination can display more information. We can reference the pagination component of PF4.

We don't have more information, I've changed the default patternfly component to be able to not show the information that we don't have

**Comment by edewit** [comment]
> The distance between the top nav bar and the left menu bar should be 24 px.

It is 24px:
![Screenshot from 2021-03-16 11-31-48](https://user-images.githubusercontent.com/51133/111295484-b6a70380-864b-11eb-9459-651ecbf399ba.png)

**Comment by xianli123** [comment]
> It is 24px:
> ![Screenshot from 2021-03-16 11-31-48](https://user-images.githubusercontent.com/51133/111295484-b6a70380-864b-11eb-9459-651ecbf399ba.png)

Sorry, I mean the distance between the top navigation bar and the left menu bar should be 24px as shown in the picture below. 
![8](https://user-images.githubusercontent.com/53931519/111301929-baf41080-868d-11eb-9f59-4afbf7be1818.png)

**Comment by edewit** [comment]
is already done:
![image](https://user-images.githubusercontent.com/51133/112813162-325a7480-907e-11eb-928c-076814ae14dd.png)
