### ISSUE TITLE
[UX review] Client - Import client

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-admin-ui#355]
Hi, @edewit I've reviewed the import client page and made some fine-tuning.

- "**Import**" button in the Client list
Clicking the "**Import**" button, there will be a modal popup, as shown in the picture below. After selecting the file and clicking the "Open" button, users will jump into the "_Import client_" page.  
<img width="1266" alt="Screen Shot 2021-02-05 at 4 52 14 PM" src="https://user-images.githubusercontent.com/53931519/107011502-ad1bb780-67d2-11eb-86b0-cc5d7cb717c8.png">

- Import client page
1. It would be nice if there was a dividing line.   
2. The length of this form should be 720 px. 
3. We can add question marks to help users better understand the tags.   
4. The Description field uses the text area component.   
5. After clicking the **Save** button, users will enter the detail page of the "Import client".   
6. Click the **Cancel** button to return the client list page, but it doesn't work now. 
7. **Capability configs** - There are some different capability configs based on the different types above.

![PageBreak_1](https://user-images.githubusercontent.com/53931519/107007116-0d0f5f80-67cd-11eb-988f-336089e08cb2.png)

The Marvel file of the "[Import client](https://marvelapp.com/prototype/7aaf345/screen/72130125)" shows more details for your reference.

**Comment by edewit** [comment]
what are the capability configs? The marvel shows 2 and says it varies on client type, as far as I know there are 2 client types (openid-connect and saml) so what is shown when the type is openid-connect?

**Comment by xianli123** [comment]
We now have 2 types of clients namely SAML2.0 and OIDC. The capability configs are shown as below:

SAML 2.0
<img width="667" alt="Screen Shot 2021-02-23 at 11 08 13 AM" src="https://user-images.githubusercontent.com/53931519/108808909-acf92580-75e2-11eb-8dfe-7f0a0c78b20e.png">

OIDC
<img width="564" alt="Screen Shot 2021-02-23 at 11 08 54 AM" src="https://user-images.githubusercontent.com/53931519/108808927-b7b3ba80-75e2-11eb-9033-039eb3a06556.png">

In the future, some new types will be added to the admin console. And then the capability configs are going to change depending on the type.
