### ISSUE TITLE
Spacing between Enable and switch is too large

### ISSUE THREAD

**Issue by mfrances17** [keycloak/keycloak-admin-ui#383]
In the sprint demo given on 2/18/21, it was brought up by a couple of attendees that the Enable label seems too far away from its switch. One comment was that it was so far away it looked like it was an entirely different control. Need to verify that the existing spacing is in accordance with Patternfly standards, and tighten up the space if necessary.

Existing layout:
![enable](https://user-images.githubusercontent.com/39063664/108416549-da1d9080-71fc-11eb-828f-43188c4e0a51.png)

**Comment by edewit** [comment]
It's using the standard [patternfly labels on a switch](https://www.patternfly.org/v4/components/switch#examples) component

![image](https://user-images.githubusercontent.com/51133/108710096-ddbe5980-7513-11eb-9fca-6f4b498c76dd.png)

**Comment by mfrances17** [comment]
Based on our discussion in this morning status, I'll file an issue with Patternfly as this affects more products than Keycloak and we want to be consistent. 

However, after thinking a bit about it, I will keep this issue open for now, as I'm wondering if they are only thinking of vertical placement and are not considering the use case of having this in a horizontal placement with other components as we are doing... in that case, if they choose not to change it, we should just change it on our project specifically.

**Comment by mfrances17** [comment]
This issue was fixed in Patternfly and rolled into master as part of this PR: https://github.com/keycloak/keycloak-admin-ui/pull/420
