### ISSUE TITLE
Fix Access Token Lifespan

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-admin-ui#405]
Access Token Lifespan does not allow -1 as a value.  This should behave the same as the old console as noted in the PR:
https://github.com/keycloak/keycloak-admin-ui/pull/373#issuecomment-786128188

**Comment by edewit** [comment]
Didn't we say that the `-1` was strange and even you didn't know if it's the same as empty. So the more user friendly way would be to allow for blank as in not set?

**Comment by ssilvert** [comment]
@edewit Should this one be closed?

**Comment by jonkoops** [comment]
@yih-wang @xianli123 What is the UX opinion on this? I can create a fix that either allows `-1` or we can come up with a nicer solution, perhaps a toggle or something?

**Comment by yih-wang** [comment]
@ssilvert Can you remind me that what's the meaning when the value is "-1"? I totally forgot that...

**Comment by jonkoops** [comment]
> @ssilvert Can you remind me that what's the meaning when the value is "-1"? I totally forgot that...

If a value of `-1` is provided here it means that the token will never expire. Seems quite user unfriendly, so it would be nice to have some UI around it. For example a checkbox that says 'Token never expires' which hides the input or disables it.

**Comment by yih-wang** [comment]
@jonkoops Do you know the default value of this field? Now the default is empty, I'm also not sure what it means...

**Comment by jonkoops** [comment]
That's a good question, I don't know exactly what the default is here when the field is empty.

**Comment by yih-wang** [comment]
@jonkoops For the pattern, we can do something like this
![image](https://user-images.githubusercontent.com/23331885/128687246-9b674aff-920e-4578-9715-3e1476953656.png)

**Comment by edewit** [comment]
@yih-wang the default it empty, guess nobody knows what that means... but my guess it's the same as `-1` I'll add the dropdown you suggested empty and `-1`

**Comment by yih-wang** [comment]
@edewit There're a lot of fields in the console use empty as the default status. They're so confused. @ssilvert Is it possible to change that to some specific values? Or at least clarify what the empty means in the tooltip.

**Comment by edewit** [comment]
@yih-wang I can make this into a general component and apply it everywhere it makes sense? Or are there other places where the text "Expires in" doesn't make sense?

**Comment by yih-wang** [comment]
When I select _Expires in_, and trying to change the number from 1 to 0. An empty state will appear between them. Maybe we can set the default to be 0, and remove the empty state? I'm not sure about the default value as I'm not sure what this field is supposed to be...

**Comment by edewit** [comment]
@yih-wang what would it mean expires in 0 minutes, wouldn't that be the same as never expires? What do you mean the default should be 0? A token that lives 0 minutes in my opinion would be useless

**Comment by yih-wang** [comment]
@edewit Ah, yes you are right. It doesn't make sense. Then I think we need to remove that value cuz currently user can set that by clicking "V" (down arrow)

**Comment by yih-wang** [comment]
Also, when I try to delete the number in the field and type in a number manually. It doesn't allow me to do that. And the dropdown changes from "Expires in" back to "Never expire" when I press the Backspace.
