### ISSUE TITLE
[UX review] Client - Credentials review

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-admin-ui#424]
Hi, @edewit I've reviewed the Client Credentials tab, there are some suggestions for this part.

A. There is a redundant line, we can remove it.  
B. The width of the form is 786px.  
C. If the user does not change the "**_Client authenticator_**", the **Save** button is disabled. Once the user has changed the "**_Client authenticator_**", the **Save** button will be enabled. Also, the client secret "**Regenerate**" button will be disabled. The changes will not be saved until users click the **Save** button. 

Please refer to the Marvel link related to the Credentials design. https://marvelapp.com/prototype/695h94c/screen/72265686

![Credentials_1](https://user-images.githubusercontent.com/53931519/110451665-61c13580-80ff-11eb-8351-c1c171fee28c.png)

**Comment by edewit** [comment]
@xianli123 we agreed in the chat that `786px` is to small so I changed it to `1024px`

**Comment by edewit** [comment]
@xianli123 so the "regenerate" button will start out as disabled? If so how can a user press it? What will trigger the enable state?

**Comment by xianli123** [comment]
> @xianli123 we agreed in the chat that `786px` is to small so I changed it to `1024px`. Or is it that some forms are 786 and some are not?

I think it can be unified with other pages.

**Comment by xianli123** [comment]
> @xianli123 so the "regenerate" button will start out as disabled? If so how can a user press it? What will trigger the enable state?

At the beginning, the Save button is disabled, and the Regenerate button is clickable. If users change the Authenticator type, the Save button will be clickable.

**Comment by edewit** [comment]
> > @xianli123 so the "regenerate" button will start out as disabled? If so how can a user press it? What will trigger the enable state?
> 
> At the beginning, the Save button is disabled, and the Regenerate button is clickable. If users change the Authenticator type, the Save button will be clickable.

So the regenerate button is always enabled

**Comment by xianli123** [comment]
Client secret doesn't always exist, it only exists when Authenticator is **Client ID and secret** or "Signed JWT with client secret". 

If users change the authenticator and don't click the Save button, the Regenerate button is disabled at this moment.

<img width="1019" alt="Screen Shot 2021-03-10 at 11 19 12 AM" src="https://user-images.githubusercontent.com/53931519/110571560-a6e27780-8192-11eb-832d-3a90553299c9.png">
