### ISSUE TITLE
[UX review] Client - Credentials review

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-admin-ui#428]
Hi, @edewit I've closed the issue #424 and opened a new issue here for more details of the Credentials review. 

Please refer to the Marvel link related to the [Credentials design](https://marvelapp.com/prototype/695h94c/screen/72265686). 

1. Save strategy: 
- Whenever users change the **_Authenticator_**, the change will not take effect until it is saved. The **Save** button is clickable only if the authenticator or its related field changes, otherwise the **Save** button is disabled. After clicking the **Save** button, there will be a confirmation modal popup to remind users the authenticator will be changed.
  <img width="645" alt="Screen Shot 2021-03-10 at 4 18 51 PM" src="https://user-images.githubusercontent.com/53931519/110598193-70215700-81bc-11eb-9694-fa349d4c3b27.png">

2. Client ID and secret: 
- The authenticator is "Client ID and secret" by default. The user can click the **Regenerate** button to generate a new secret. 
  <img width="795" alt="Screen Shot 2021-03-10 at 4 23 49 PM" src="https://user-images.githubusercontent.com/53931519/110598856-3270fe00-81bd-11eb-9ce6-417c30051e6a.png">

- After clicking the **Regenerate** button, there will be a modal popup. The same thing happens to **Registration access token.**
  <img width="708" alt="Screen Shot 2021-03-10 at 4 25 27 PM" src="https://user-images.githubusercontent.com/53931519/110598960-57657100-81bd-11eb-94ae-f7cc4b663de2.png">

3. Signed JWT with client secret: 
- If the user changes the **_Authenticator_** to "**Signed JWT with client secret**", the **Save** button will be enabled, and the **Regenerate** button will be disabled. After clicking the **Save** button, there will be a confirmation modal popup.
  <img width="780" alt="Screen Shot 2021-03-10 at 4 30 10 PM" src="https://user-images.githubusercontent.com/53931519/110599598-00ac6700-81be-11eb-9b04-c7afa04b1354.png">

4. X509 certificate: 
- If the user changes the **_Authenticator_** to "**X509 certificate**", the user has to fill in the **_Subject DN_**, otherwise, the **Save** button is not clickable. After filling in the **_Subject DN_** and clicking the **Save** button, there will be a confirmation modal popup.
  <img width="782" alt="Screen Shot 2021-03-10 at 4 34 34 PM" src="https://user-images.githubusercontent.com/53931519/110600177-9c3dd780-81be-11eb-867d-d14e7ee2ce08.png">

5. Signed JWT: 
- It's better to use a scrollable list to show the Signature algorithm.
  <img width="1124" alt="Screen Shot 2021-03-10 at 4 37 20 PM" src="https://user-images.githubusercontent.com/53931519/110600709-31d96700-81bf-11eb-81be-093b1c94d27c.png">

6. Header:
- There is a redundant line, we can remove it.
 ![C1](https://user-images.githubusercontent.com/53931519/110601731-3b170380-81c0-11eb-8c08-b13ed1efe18d.png)

**Comment by edewit** [comment]
@xianli123 what is a scrollable list?

**Comment by xianli123** [comment]
It means we don't need to show all options. We can use the scroll bar to view the remaining options as shown in the picture below.
<img width="435" alt="Screen Shot 2021-03-11 at 2 57 00 PM" src="https://user-images.githubusercontent.com/53931519/110748877-51ce6080-827b-11eb-8ff7-228878df43a0.png">

**Comment by xianli123** [comment]
hi @edewit, I found the box next to the menu bar on the left. Can we create a gap between the box and the menu bar? We can set the distance between the box and the menu bar to 24px. 
<img width="684" alt="Screen Shot 2021-04-13 at 3 16 58 PM" src="https://user-images.githubusercontent.com/53931519/114512391-a8a8ca80-9c6b-11eb-9741-4ebdac36f46e.png">

**Comment by xianli123** [comment]
hi @edewit, If users select "Signed JWT" as the client authenticator, an option called "Any algorithm" should be added in the "Signature algorithm" dropdown, which is the default option. Please refer to the tooltip description mentioned "JWT algorithm, which the client needs to use when signing a JWT for authentication. **_If left blank, the client is allowed to use any algorithm._**"

<img width="1049" alt="Screen Shot 2021-05-17 at 3 52 49 PM" src="https://user-images.githubusercontent.com/53931519/118456952-00839700-b72c-11eb-9601-327097044fff.png">
