### ISSUE TITLE
[UX review] User federation - LDAP

### ISSUE THREAD

**Issue by yih-wang** [keycloak/keycloak-admin-ui#436]
### **High priority**

[Empty state]

1. When hovering on the cards, the mouse pointer doesn't change to a hand.

[Creation page]

2. The old console provides ldap as the Console display name by default. It's a good feature to keep in the new console.
![image](https://user-images.githubusercontent.com/23331885/115397921-2e52ea00-a219-11eb-9442-34e0018e736c.png)
4. Change the value of Vendor should make some differences to "Username LDAP attribute", "RDN LDAP attribute", "UUID LDAP attribute" and "User Object Classes" in the _LDAP searching and updating_ section. I don't see this in the new console, not sure if there's a discussion happened before. Just bring this issue for your reference.
![image](https://user-images.githubusercontent.com/23331885/110935145-ff1fa200-8369-11eb-9f23-909969396207.png)
6. Clicking the Test button doesn't give me any feedback now. A success/error notification is supposed to display.
![image](https://user-images.githubusercontent.com/23331885/110936864-7d7d4380-836c-11eb-90ce-a8034ba4cb80.png)
7. When the bind type is none, the "Bind DN" and "Bind credentials" are not supposed to show. And the Test button only works for test connection. 
![image](https://user-images.githubusercontent.com/23331885/110936329-b1a43480-836b-11eb-8400-3697b18bfcad.png)
8. Following the last point, I think we can add some help info to the Test button. We used to have two separate buttons to test connection and authentication. But now, there is only one Test button to test both. And it is only used to test connection as mentioned in the last point. Maybe change the name of it to "Test connection and authentication" and "Test connection"?
13. The Periodic Full Sync and the Periodic Changed Users Sync are supposed to have toggles control them.

### **Low priority**

[Creation page]

1. The asterisks and the help icons don't keep in the same rows with some of the labels, I remember @jenny-s51 got a same comment during the App Service meeting. Maybe we can solve it as a global issue.
![image](https://user-images.githubusercontent.com/23331885/110934510-0eeab680-8369-11eb-9bbd-ff6dc4926623.png)
5. The Connection pooling toggle used to trigger a set of settings like the screen shows, but I don't see it in the new console. Not sure whether this has been discussed as well.
![image](https://user-images.githubusercontent.com/23331885/110935413-5887d100-836a-11eb-82f8-9bfa0d71a411.png)
9. I noticed that there is an extra button available in the creation page. Is it supposed to be added to the new console?
![image](https://user-images.githubusercontent.com/23331885/110937573-84f11c80-836d-11eb-83b8-09d0c4bae07e.png)
10. The "Allow kerberos authentication" used to trigger these settings in the old console
![image](https://user-images.githubusercontent.com/23331885/110937598-8e7a8480-836d-11eb-99d9-f7daa500035e.png)
11. I think we can make some improvements to the validation messages. I remember that patternfly suggests that we use a voice that not blame the users. So maybe something like "Users DN wasn't provided" is better. I'll ask the content writer's advice on that.
![image](https://user-images.githubusercontent.com/23331885/110937781-d699a700-836d-11eb-834b-ccb0cefd0727.png)
12. A suggestion but not a requirement. It's better to use a time picker here to replace selecting the hour and minute separately from the dropdowns. The time picker pattern - https://www.patternfly.org/v4/components/time-picker#examples
![image](https://user-images.githubusercontent.com/23331885/110938321-a6063d00-836e-11eb-9818-c92f93883c4f.png)

[Detail page]

7. The space between the header and the form seems a bit large, and a divider line is missing. Reference - https://marvelapp.com/prototype/ecjc94b/screen/72098368
![image](https://user-images.githubusercontent.com/23331885/110925573-5586e380-835e-11eb-8a67-519064424748.png)
15. The vendor is not supposed to be changeable after creation.
![image](https://user-images.githubusercontent.com/23331885/110937013-ba493a80-836c-11eb-8502-90efebe7247d.png)

@mfrances17

**Comment by yih-wang** [comment]
Hi @mfrances17, I reviewed all the issues again and separate them as high/low priority issues. The high-priority issues will be involved in the testing.

**Comment by mfrances17** [comment]
> Just notice a new issue - after a provider is created, the screen should jump to the detail page instead of the provider list.

If that's what you want, sure. Personally, I think when you create something (vs. edit something) it should go to the listing page so you see it created as a new entity. If we don't navigate away, the user will need to actually notice the display of the notification message in the next few seconds, there's no other indicator since the creation page and detail page are one in the same. 

Also, would like to know the reasoning behind staying on the same page - you had the opportunity to add all configuration info during create. This design would only makes sense to me if you were only partially listing configuration info during create and then the details has additional config.

**Comment by yih-wang** [comment]
> > Just notice a new issue - after a provider is created, the screen should jump to the detail page instead of the provider list.
> 
> If that's what you want, sure. Personally, I think when you create something (vs. edit something) it should go to the listing page so you see it created as a new entity. If we don't navigate away, the user will need to actually notice the display of the notification message in the next few seconds, there's no other indicator since the creation page and detail page are one in the same.
> 
> Also, would like to know the reasoning behind staying on the same page - you had the opportunity to add all configuration info during create. This design would only makes sense to me if you were only partially listing configuration info during create and then the details has additional config.

Thanks for the insights. This issue has been discussed during the design process. In the new console, we tried to simplify most of the creation process, e.g. client, identity provider. That will be more friendly to the novice - they can complete the creation by only filling the basic configurations. So for most entities in Keycloak, users may want to make advanced configurations after creation (include filling advanced fields, adding mappers, adding client scopes, etc.). That's why we choose to return to the detail page, but not the list.

Specifically for the LDAP provider, the creation page is rather the same as the detail page for now (as the wizard style isn't applied yet), but we still choose to return to the detail page for two reasons. One is for consistency, we want different entities to have the same behavior around the console. The other reason is users are likely to add more mappers after creation. The LDAP data format is hard to match the Keycloak data format in the real case. Also, they may want to go to the Actions dropdown to sync or import users. That's why we want it to stay on the detail page. Does it make sense to you?

**Comment by mfrances17** [comment]
Reopening since every time we merge a partial fix in, it closes this issue automatically when there are still other things to do.

**Comment by mfrances17** [comment]
I understand what you are saying but I even recall demoing an early version of the react Admin UI at the sprint end demo that stayed on the page after it was created and at least two designers at the meeting commented that after clicking create it should navigate back to the card view.

**Comment by mfrances17** [comment]
Also, with the PR that was just now merged, all of the high priority issues (1-7) that were separated out as needed for UX testing should now be fixed in the latest master branch.

**Comment by yih-wang** [comment]
@mfrances17 I remember that I explained why the Keycloak screen stays on the detail page during the meeting. And Alessandro mentioned that the 3scale has the same behavior. I'm trying to find the recording but can't locate which date the meeting was... Do you remember that?

**Comment by yih-wang** [comment]
Hi @mfrances17 , I found that in the new UI, the Test button is disabled all the time even if I fill the Bind DN and pw. Also, it will be hidden when the Bind type is none. As the Test here also tests the connection above, it should be displayed all the time. See the images below.
![image](https://user-images.githubusercontent.com/23331885/118946801-55701900-b989-11eb-98a0-e708ad94f9a9.png)
![image](https://user-images.githubusercontent.com/23331885/118946846-5f921780-b989-11eb-8101-a64bcfc2441d.png)

**Comment by yih-wang** [comment]
Another issue is the Import user toggle should be turned on by default.
![image](https://user-images.githubusercontent.com/23331885/118949754-20b19100-b98c-11eb-9832-fb4a8877d6a9.png)

**Comment by mfrances17** [comment]
Thanks @yih-wang, I'd be interested in hearing what the user feedback is with regard to the navigation after submit. Ultimately, I will do whatever you want me to do :) it just seemed like questionable choice to me.  

I submitted a PR with your requested changes to the test button and import users toggle.

**Comment by yih-wang** [comment]
@mfrances17 Thanks for the updates. I just found a new issue - 

There shouldn't be a tab bar on the LDAP creation page. You can reference other creation pages e.g. Roles, Identity providers. Also, we can change the title here to "Add LDAP provider".

![image](https://user-images.githubusercontent.com/23331885/120585092-b573be80-c463-11eb-96ef-b59e5cc5246c.png)

**Comment by yih-wang** [comment]
Close this issue for now. Will open new issues for the user testing finding ones.
