### ISSUE TITLE
Add User Fed LDAP mappers to keycloak-admin

### ISSUE THREAD

**Issue by mfrances17** [keycloak/keycloak-admin-ui#449]
We need to add something to keycloak-admin for ldap mappers. Here is the request/response from the legacy admin console UI:
**Request:**
`GET /auth/admin/realms/master/components?parent=f1da61f9-08f7-4dc5-83dd-d774fba518d4&type=org.keycloak.storage.ldap.mappers.LDAPStorageMapper`

**Response:**
```
[
  {
    "id":"699b72e5-b936-41b9-98fc-5d5b3ec5ea6f",
    "name":"username",
    "providerId":"user-attribute-ldap-mapper",
    "providerType":"org.keycloak.storage.ldap.mappers.LDAPStorageMapper",
    "parentId":"f1da61f9-08f7-4dc5-83dd-d774fba518d4",
    "config":
      {
        "ldap.attribute":["cn"],
        "is.mandatory.in.ldap":["true"],
        "always.read.value.from.ldap":["false"],
        "read.only":["true"],
        "user.model.attribute":["username"]
      }
    },
.
. (other mappers)
.
```
I would imagine we'd need to add something like `componentMapperRepresentation` and it would probably look something like this:

```
export default interface ComponentMapperRepresentation {
    config?: Record<string, any>;
    id?: string;
    name?: string;
    providerId?: string;
    providerType?: string;
    parentID?:string;
}
```
I'm just not sure what other magic needs to happen to get this into keycloak-admin.

**Comment by edewit** [comment]
This can already be done with the existing `components.find` like this:

```typescript
adminClient.components.find({parent: 'f1da61f9-08f7-4dc5-83dd-d774fba518d4', 
    type:"org.keycloak.storage.ldap.mappers.LDAPStorageMapper"});
```
