### ISSUE TITLE
Use @snowpack/plugin-dotenv for environment configuration?

### ISSUE THREAD

**Issue by xgp** [keycloak/keycloak-admin-ui#457]
I'd like to be able to easily change some environment-specific variables (e.g. The Keycloak server url), rather than having to find every place in the code where they're hard coded. Has any thought been given to using something like `dotenv` for such things? I'd be happy to submit a patch to use the snowpack plugin: https://github.com/snowpackjs/snowpack/tree/main/plugins/plugin-dotenv

**Comment by ssilvert** [comment]
I was just looking at that last week.  I think it's probably going to be needed at some point, but I don't understand your use case.  What exactly are you trying to do?

**Comment by xgp** [comment]
I want to be able to change the configured Keycloak server url so that I could host the admin UI on a different host/domain from Keycloak.

**Comment by xgp** [comment]
E.g. in `src/context/auth/keycloak.ts` the

**Comment by ssilvert** [comment]
> E.g. in `src/context/auth/keycloak.ts` the `keycloakAuthUrl` gets built from the host you loaded the UI from. I'd like to be able to specify it directly so I can have Keycloak and the admin UI on a different host.

That's really interesting and I've often wondered if that would be useful.  Can you elaborate some more on why you want to do that?  Is it something you would want to do in production?

**Comment by xgp** [comment]
Yes, I would do it in production. 
- It decouples the need to release the admin UI and Keycloak as a single unit. If I'm iterating on an admin theme/customization, I can change and deploy that easily without needing a redeploy of Keycloak. 
- It allows the admin UI and Keycloak to be independently scaled (e.g. put the admin UI on a CDN).

**Comment by xgp** [comment]
I can also see this project as more of a scaffolding for building admin "apps" on top of Keycloak. Unlike the single purpose of the current admin UI, I would use this as a starter when building an application that has a lot of interaction with the admin API. 

I've done that before as a separate app, which uses the admin API library, but I always found that I was re-implementing stuff that already exists as part of the admin UI. Because this is React component-based, it's easier to reuse.

**Comment by ssilvert** [comment]
That all sounds good.  Short answer is, yes, we would welcome your PR.

**Comment by edewit** [comment]
@xgp The url in `keycloak.ts` is for local development only it's not used when the content is served up by keycloak. It's the only place the location is used. (apart from some import scripts) All communication with keycloak is done via the [admin-client](https://github.com/keycloak/keycloak-nodejs-admin-client) you can create a new UI for any keycloak instatance. By overriding this admin client, I've created an electron app that does just that, like this:

```typescript
const kcAdminClient = new KcAdminClient();
// initialize it with url and token or password, then render UI:
<KeycloakAdminConsole adminClient={kcAdminClient} />
```
see: https://github.com/edewit/keycloak-admin-console/blob/master/app/index.tsx#L22

**Comment by xgp** [comment]
> The url in keycloak.ts is for local development only it's not used when the content is served up by keycloak

Thanks @edewit but it looks like that's where the URL for the admin client gets initialized. I did a test where I replaced the `url` value in the `kcAdminClient.init` call, deployed the result of a `yarn run build` to a webserver, and it correctly pointed to the Keycloak instance I specified in that URL.

**Comment by edewit** [comment]
Sure, but like I said it's mean for local development that is why it's not configurable the standard way production way to use it would be that it's served from keycloak and that it connects back to itself.

**Comment by edewit** [comment]
@xgp although it wouldn't hurt to make this configurable.

**Comment by xgp** [comment]
Thanks for your help! I’ll submit a PR.

**Comment by ssilvert** [comment]
@xgp Have you made any progress on this?  

I'm interested to know if you can even get it working with the new admin console served from a host that is different from the keycloak server.

**Comment by xgp** [comment]
Yes. I have the admin client setup and login redirect working properly, but there seems to be an assumption about the “proxy” that gets created by snowpack. Even though I set up the KeycloakAdminClient with the proper parameters, it seems to still send requests through the same host it is served from, requiring there to be some kind of proxy. I’ll keep working on it and post progress here. Can I send you my in-progress PR?

**Comment by edewit** [comment]
@xgp we did the proxy to get rid of CORS, I don't know if you can configure keycloak to add the CORS headers on the admin rest endpoints. The proxy only gets created when running dev mode with `yarn start`, the endpoint that is used is determined by the [`baseUrl`](https://github.com/edewit/keycloak-admin/blob/398ca19ec1763c6537292e14e015abe8206ada76/src/context/auth/keycloak.ts#L22)

**Comment by edewit** [comment]
just mark the PR `WIP` and send it then we can all have a look

**Comment by ssilvert** [comment]
I tried this myself and got a very strange result.  The serverinfo request works fine, but the whoami request gets a CORS error and thus the app fails to load.

**Comment by xgp** [comment]
I see the same. I'm working on trying to figure out why `whoami` fails on a CORS error even when other requests succeed.

**Comment by xgp** [comment]
@edewit I think you're right. It looks like adding CORS headers to (some) admin REST endpoints on the Keycloak server isn't currently set up. In `serverinfo`, it does return a `AdminCorsPreflightService` if it's an `OPTIONS` request, but not in `whoami` and others.

**Comment by ssilvert** [comment]
@xgp I'm going to take a look at the server code.  If lots of the admin REST API need CORS support then I'll discuss with others whether or not we want to fix it.

**Comment by ssilvert** [comment]
@xgp I got it working.  But it does require server side changes.  https://github.com/keycloak/keycloak/pull/7891

**Comment by xgp** [comment]
@ssilvert This great. Thanks for doing/sharing this. Do you think this is something we could add to a future version of the server?

**Comment by ssilvert** [comment]
@xgp Yes, it was just added.

I will caution you though.  Stian Thorgersen, chief architect of Keycloak, told me "It really only works for a demo/prototype scenario. You wouldn't want to use it for real production use-cases for a number of reasons. One obvious thing is that a lot of folks don't expose admin endpoints at all to the public. Ideally also the admin console should be secured in a different way, where the client-side doesn't get access to the tokens directly. In essence for the most secure setup you'd want the admin console on the same domain as Keycloak."

I wouldn't say flat out, "Don't do it."  But be careful and know the risks.

**Comment by xgp** [comment]
@ssilvert Thanks for the additional context on security and risks.

Now that the WhoAmI change is in Keycloak master, does that mean it will be released in the next official release of Keycloak?

**Comment by ssilvert** [comment]
@xgp Yes.  It will be in Keycloak 13.

**Comment by ssilvert** [comment]
I believe this PR https://github.com/keycloak/keycloak-admin-ui/pull/482 completes this issue.
