### ISSUE TITLE
Cancel on modals

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-admin-ui#459]
Looks like the PatternFly rule for cancel buttons on modals is that if there is user input on the modal then there should be a cancel button (rendered as a link).  Otherwise, the only way to close the modal is the X in the upper righthand corner.

We need to fix this throughout the console and the designs.

@yih-wang If you agree, Erik will make the changes.

**Comment by yih-wang** [comment]
@ssilvert Can you point out where to find the guidelines? I just checked the Patternfly website and didn't find the instructions on how to use the Cancel button. But I noticed the modal example that doesn't include an input also has the Cancel button. 
![image](https://user-images.githubusercontent.com/23331885/112412521-9a951780-8d59-11eb-9dac-b41818edfb24.png)

I can't remember I have seen a modal without the Cancel button in our products. Will make a confirmation with Patternfly team.

**Comment by ssilvert** [comment]
I haven't found any written guidelines on this issue.  I'm just going by the examples I see.

The example you show is something that requires user input because a decision has to be made.  In that case, the "Cancel" button itself is the user input.

Maybe the rule would better be stated as, "All modals should include a Cancel button except in the case where it is purely informational."

It will be good to get a formal decision from PatternFly.  Thanks for looking into it.

**Comment by yih-wang** [comment]
@ssilvert Seems that Patternfly has a quite flexible policy for the Cancel button.

> Maybe the rule would better be stated as, "All modals should include a Cancel button except in the case where it is purely informational."
I agree with that. Specifically to the use cases around the admin console (e.g. the Join Group modal), the modal which contains a primary button should also contain the Cancel button.

**Comment by ssilvert** [comment]
> @ssilvert Seems that Patternfly has a quite flexible policy for the Cancel button.
> 
> > Maybe the rule would better be stated as, "All modals should include a Cancel button except in the case where it is purely informational."
> 
> I agree with that. Specifically to the use cases around the admin console (e.g. the Join Group modal), the modal which contains a primary button should also contain the Cancel button.

OK.  @edewit if you agree, we will go with the above rule and make changes accordingly.
