### ISSUE TITLE
[UX review] Client - Client scopes evaluate

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-admin-ui#464]
Hi @edewit, I've reviewed the client scopes evaluate page and made some fine-tuning.

**1. Evaluate page review:**

> ![ClientScopeEvaluate_1](https://user-images.githubusercontent.com/53931519/112444884-78b38900-8d89-11eb-8925-d0fad3194f45.png)

- A. Click the help info that will trigger the popover of the introduction. 
- B. The distance from the field to the sides should be 24px.  
- C. Every tag in the Jump to section is followed by a question mark.

**2. Effective protocol mappers review:** 

> ![ClientScopeEvaluate_2](https://user-images.githubusercontent.com/53931519/112445340-fb3c4880-8d89-11eb-9d84-576f09992bad.png)

- A. We can divide these protocol mappers into several pages and then add pagination to make it easier for the user to view. In addition, the attribute "Type" is missing.
![ClientScopeEvaluate_3](https://user-images.githubusercontent.com/53931519/112446702-718d7a80-8d8b-11eb-9bdb-c395b831dc14.png)

- B. Titles' initials are capitalized.

**3. Effective role scope mappings review:**

> <img width="1035" alt="Screen Shot 2021-03-25 at 4 50 57 PM" src="https://user-images.githubusercontent.com/53931519/112445705-65ed8400-8d8a-11eb-996a-807b48aa5b1f.png">

If there are composite roles, we can refer to the design of composite roles in **_[Service account roles](https://marvelapp.com/prototype/f058374/screen/71931941)_**. After **_Service account roles_** is completed, we can directly apply it on this page.

**Comment by edewit** [comment]
> 3. Effective role scope mappings review:
> If there are composite roles, we can refer to the design of composite roles in Service account roles. After Service account roles is completed, we can directly apply it on this page.
I don't understand this point do you mean that the `service account roles` need to be included in the page as well?

**Comment by xianli123** [comment]
I mean we can put it aside for a while, wait until the "**Service account role**" is done, and then do this part. WDYT?

**Comment by edewit** [comment]
Okay
