### ISSUE TITLE
Groups paths need collapsing

### ISSUE THREAD

**Issue by edewit** [keycloak/keycloak-admin-ui#518]
On [UXD design](https://marvelapp.com/prototype/228971ig/screen/78140650) at point `D` we need to make the path shorter if there isn't enough room. We could based on the window size have some sort of constant number of groups at which point we should do this, but this solution seems to me to be a bit sloppy, I rather have it a constant. Or could we solve this with some sort of very cool css?

**Comment by edewit** [comment]
@ssilvert @jenny-s51 @mfrances17 any ideas on how to solve this?

**Comment by edewit** [comment]
I like this solution what do you think @xianli123

**Comment by xianli123** [comment]
IMHO, this solution is suitable for textual content rather than Groups. Regarding Groups, it is necessary to show the path and level of those groups. I think we should display the root group at least. What do you think? @edewit @yih-wang

**Comment by edewit** [comment]
fixed in https://github.com/keycloak/keycloak-admin-ui/pull/709
