### ISSUE TITLE
Realm selector: update search filter to list only filtered realms

### ISSUE THREAD

**Issue by jenny-s51** [keycloak/keycloak-admin-ui#577]
> When I type something into the realm selector search box, the filtering works, though the "recent" realms show first and the searched realm is hidden by the "Create Realm" button underneath and a user cannot see it until they scroll through the recent realms first.
> 
> <img alt="Screen Shot 2021-05-03 at 11 04 00 AM" width="308" src="https://user-images.githubusercontent.com/32821331/116894190-ca102d00-abff-11eb-9575-1002a86dae78.png">
> 

We should hide all the recent used realms if a user enters a search input that doesn't match any of the recent realms.

_Originally posted by @jenny-s51 in https://github.com/keycloak/keycloak-admin-ui/issues/576#issuecomment-831383240_

**Comment by edewit** [comment]
fixed in #580
