### ISSUE TITLE
Server principal field not populating

### ISSUE THREAD

**Issue by mfrances17** [keycloak/keycloak-admin-ui#591]
In User Federation > LDAP settings, the "Server principal" field is not displaying the data value, even though the data is there and it is read from and can write to the backend correctly. If you type a value, it writes to the backend correctly and the new/updated value can be viewed in the old console. But if you try to view it in the new console, it is empty. 

The field uses the correct data point - config.serverPrincipal[0], and it is coded the same as the "Kerberos realm" above and "Key tab" below. Both of those fields are displayed correctly. Only the server principal field has this issue. I've checked the value in the network calls a thousand times, it is the correct value, it's just not displaying.

Also, the same datapoint of config.serverPrincipal[0] is pulled in and displayed correctly in the separate Kerberos provider configuration, as are the kerberos realm and keytab fields. There's no difference in the calls.

**Comment by mfrances17** [comment]
Interestingly enough, I moved the Server principal field out of the block that checks for useWatch, and the field is displayed correctly. So this might be a bug/problem with how useWatch works with multiple fields, as the other fields in useWatch work fine:

**Server principal** field inside useWatch:
![inside-usewatch](https://user-images.githubusercontent.com/39063664/117369308-bfb99180-ae92-11eb-9f6f-d1fd0afce5b3.png)

**Server principal** field outside useWatch:
![outside-usewatch](https://user-images.githubusercontent.com/39063664/117369413-e1b31400-ae92-11eb-8a07-7c0ad0dc327d.png)

**Comment by edewit** [comment]
@mfrances17 is this still an issue? I couldn't reproduce this.

**Comment by mfrances17** [comment]
@edewit you are correct, i re-tested this and it's working as expected. i might've fixed it while i was finishing up LDAP mappers. closing this issue.
