### ISSUE TITLE
Packages that need upgrades

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-admin-ui#594]
Recommended package upgrades:
https://issues.redhat.com/browse/KEYCLOAK-18025
https://issues.redhat.com/browse/KEYCLOAK-18026
https://issues.redhat.com/browse/KEYCLOAK-18027

**Comment by edewit** [comment]
isn't this done by dependabot?

**Comment by ssilvert** [comment]
Bruno is using a different tool to find recommended package upgrades.  He created JIRAs for each one so I created this issue to track.  I'm sure eventually the upgrades will be picked up by dependabot and we will just close this.

**Comment by jonkoops** [comment]
I believe Dependabot should keep all dependencies up-to-date, it does however hold some back if there are version conflicts in the dependency tree.

I unfortunately cannot see the aforementioned issues, but I could take a look if someone can give me access or post the affected dependencies here.

**Comment by jonkoops** [comment]
All our dependencies are kept up-to-date, closing this issue.
