### ISSUE TITLE
Realm settings(keys): providers list updates

### ISSUE THREAD

**Issue by jenny-s51** [keycloak/keycloak-admin-ui#603]
Sort by priority and add delete functionality to providers list as shown in: https://marvelapp.com/prototype/99i86j9/screen/75627938

**Comment by ssilvert** [comment]
@jenny-s51 Should this issue be closed?

**Comment by jenny-s51** [comment]
@yih-wang @xianli123 was it intentional to exclude the form field for "priority" in the modal design here? In the mock for the providers list, it says the providers should be sorted by priority. 

See https://marvelapp.com/prototype/99i86j9/screen/75627941 and https://marvelapp.com/prototype/99i86j9/screen/75627938.

**Comment by jenny-s51** [comment]
@ssilvert just posted in Zulip - waiting on a response from Haley and Kun

**Comment by yih-wang** [comment]
@jenny-s51 Yes, the "priority" field is replaced by the drag & drop handlers in the list. If you check the annotation A in this screen https://marvelapp.com/prototype/99i86j9/screen/75627938, you will see the explanation.

**Comment by jenny-s51** [comment]
@yih-wang what would be a good way to inform the user that dragging items changes priority? Per the link you shared the priority is not listed in the design for the new providers table, so they need a way to know that the list is sorted by priority.

**Comment by yih-wang** [comment]
@jenny-s51 That is a good point. I can think of two solutions to clarify that - 

1. Add tooltip when hovering, add confirmation modal after changing order.
![image](https://user-images.githubusercontent.com/23331885/128658370-34de8d16-37d5-44a5-b050-7f46aee21bd9.png)

2. Remove the handlers in the list and use a modal to manage the orders. reference the design in Identity providers - https://marvelapp.com/prototype/55c2d8f/screen/75697044

What do you think?
