### ISSUE TITLE
failed to initialize keycloak

### ISSUE THREAD

**Issue by afonsobspinto** [keycloak/keycloak-admin-ui#61]
Hello. I was trying to evaluate if this keycloak-admin-ui would be a viable alternative to the current admin console but I was stopped at the setup.

- [x] Keycloak Running at 8180
- [x] Client added using security-admin-console-v2.json
- [x] Dependencies installed:
- [ ] Starting server: `failed to initialize keycloak`

![image](https://user-images.githubusercontent.com/19196034/92147662-5836d800-ee13-11ea-99dc-a77b20c68f2b.png)

It looks like a wrong path problem and potentially a missing dependency? 
I look forward to hearing back from you on this

**Comment by edewit** [comment]
Can you supply what is in the console log of the browser? This project is still very early stages and therefore can't be a viable alternative yet, but it will..

**Comment by afonsobspinto** [comment]
![image](https://user-images.githubusercontent.com/19196034/92378317-89f2bc00-f0fd-11ea-95dd-3be9384442b0.png)
I understand, I appreciate your honesty and wish you the best of luck with this project

**Comment by edewit** [comment]
Strange this `auth/` part of the keycloak.json it should be `http://localhost:8080/keycloak.json` you have your own keycloak and started this app with `yarn start` right?

**Comment by afonsobspinto** [comment]
I do.
Here are my steps:

- Keycloak Running at 8180:
![image](https://user-images.githubusercontent.com/19196034/92398816-25e1ef00-f121-11ea-9ec8-77ebeeb7dcae.png)

- Dependencies installed:
![image](https://user-images.githubusercontent.com/19196034/92399022-83763b80-f121-11ea-8775-5eba9822cc00.png)

- And running with yarn start results in the aforementioned issue:
![image](https://user-images.githubusercontent.com/19196034/92399129-ae608f80-f121-11ea-96e6-8f593e92bdbd.png)

I'm not sure if this will be useful as I didn't pay much attention to what was going on under the curtains I was just messing around, but I noticed that if create a folder auth under public and move https://github.com/keycloak/keycloak-admin-ui/blob/master/public/keycloak.json inside I no longer have that error but:
![image](https://user-images.githubusercontent.com/19196034/92399512-4fe7e100-f122-11ea-81e8-b81c87fccda2.png).
