### ISSUE TITLE
[UX Review] Groups

### ISSUE THREAD

**Issue by yih-wang** [keycloak/keycloak-admin-ui#629]
[Empty state]
1. Is it possible to remove the toolbar in the Empty state? As there are no groups yet, the toolbar doesn't have any use here.
![image](https://user-images.githubusercontent.com/23331885/119337208-21fef880-bcc1-11eb-922a-c51804e81bac.png)
2. Maybe we can disable the Actions when there are no groups. The search group function doesn't make sense at the time.
@edewit

**Comment by yih-wang** [comment]
[Search globally]

1. A breadcrumb is missing so I can't find a way to return to the group list.
![image](https://user-images.githubusercontent.com/23331885/119338950-33e19b00-bcc3-11eb-864f-a0ff82306267.png)

2. I'm doubting this page is forgot to be updated so its style is obviously not aligned with all other pages (it's in the old style we used to apply). Can we adjust the background and table the same with other pages?
![image](https://user-images.githubusercontent.com/23331885/119339749-24af1d00-bcc4-11eb-98a7-5d3ea52344f8.png)

3. The divider line is too far away from the toolbar, is it possible to narrow the space between them?
![image](https://user-images.githubusercontent.com/23331885/119342276-6c837380-bcc7-11eb-88a4-be0b1075a799.png)

**Comment by yih-wang** [comment]
The header here should be the Group name, not always the "Groups"

![image](https://user-images.githubusercontent.com/23331885/119343163-a739db80-bcc8-11eb-86fe-a406df1fb406.png)

**Comment by edewit** [comment]
> The paginations are not aligned with each other. Also I found it's a generic issue around the console. Can we fix it by changing the template?

What do you mean by this? I think it's correct to show that it's showing items 1 till 2 in this case?

**Comment by edewit** [comment]
> The header here should be the Group name, not always the "Groups"

"Groups" in this case is the root it's not a specific group, if it's unclear it could also be called "Group list" maybe?

**Comment by yih-wang** [comment]
> > The paginations are not aligned with each other. Also I found it's a generic issue around the console. Can we fix it by changing the template?
> 
> What do you mean by this? I think it's correct to show that it's showing items 1 till 2 in this case?

Here I mean the top pagination and the bottom pagination are not aligned. The bottom pagination has a right margin but the top one doesn't.

**Comment by yih-wang** [comment]
> > The header here should be the Group name, not always the "Groups"
> 
> "Groups" in this case is the root it's not a specific group, if it's unclear it could also be called "Group list" maybe?

To align with the other screens (Clients, Users, Roles, etc.), the header should be the group name, and the breadcrumb is better to be "Group details". In this case, "bao" in breadcrumb should be "Groups details", "Groups" in header should be "bao".

**Comment by edewit** [comment]
> 
> Here I mean the top pagination and the bottom pagination are not aligned. The bottom pagination has a right margin but the top one doesn't.

This seems to be something patternfly does, I don't know how to fix this:

![image](https://user-images.githubusercontent.com/51133/120273471-d21ac580-c2ae-11eb-8873-bde9f3f1c9c5.png)

**Comment by yih-wang** [comment]
I've reviewed the Move to function and seems it still follows the old design. The new design (updated in March) has been added to the spreadsheet. You can also check the link here to see if there's any question. https://marvelapp.com/prototype/228971ig/section/1315562

**Comment by edewit** [comment]
@yih-wang we can close this issue right? Most of the items here are resolve if not all
