### ISSUE TITLE
[UX Review] Realm settings - Theme

### ISSUE THREAD

**Issue by yih-wang** [keycloak/keycloak-admin-ui#637]
I found the behavior of the Supported locales dropdown is not aligned with PF4. https://www.patternfly.org/v4/components/select/#multiple

1. Each time I select an option, the dropdown menu will be collapsed. It should keep opening as it's a multiple select dropdown.
2. When I click Show more or Show less, or remove one of the chips, the dropdown menu will be opened/closed.
3. The Save doesn't work on this page. So as the revert.

@jenny-s51

**Comment by jenny-s51** [comment]
save/revert will be fixed by #633

**Comment by jenny-s51** [comment]
Closed via #646 and #633
