### ISSUE TITLE
[UX Review] Realm settings - Login

### ISSUE THREAD

**Issue by yih-wang** [keycloak/keycloak-admin-ui#638]
1. The Duplicate emails should be disabled OFF instead of ON when "Email as username" and "Login with email" are not both off.
2. Can we get rid of the grey borders of the two sets of switches?
![image](https://user-images.githubusercontent.com/23331885/119490894-ebdc7a00-bd8f-11eb-8858-b85ca01cfbb4.png)
@jenny-s51

**Comment by jenny-s51** [comment]
Borders resolved in #631

@yih-wang I cannot replicate the switch behavior you are seeing - the functionality here was implemented such that the Duplicate emails should be always set to disabled OFF when "Email as username" and "Login with email" are not both off.

**Comment by yih-wang** [comment]
@jenny-s51
