### ISSUE TITLE
[UX Review] Realm settings - Keys

### ISSUE THREAD

**Issue by yih-wang** [keycloak/keycloak-admin-ui#639]
[Keys list]

1. A filter is missing in the Keys list. Reference the design - https://marvelapp.com/prototype/99i86j9/screen/75627935
2. As the advanced search is already available in PF, the search box should be replaced with it. Reference the screen above.
3. The providers should be clickable and connect to the provider detail page.

@jenny-s51

**Comment by yih-wang** [comment]
@jenny-s51 I've noticed the second issue hasn't been addressed yet. The current PF advanced search doesn't support dropdowns in it. But @agagancarczyk has already figured out some ways to solve that. Maybe you can share the component.

**Comment by ssilvert** [comment]
I think the second issue can be addressed after 1.0.  @yih-wang please let me know if you think it's important to address it sooner.

**Comment by yih-wang** [comment]
@ssilvert That makes sense. Then I'll close this issue and create a separate one for post 1.0

**Comment by jonkoops** [comment]
@yih-wang You can change the milestone of the issue as well, no need to make a new one.

**Comment by yih-wang** [comment]
@jonkoops Just because this issue includes some issues that are done ;)

**Comment by jonkoops** [comment]
> @jonkoops Just because this issue includes some issues that are done ;)

Ahhh, yes. That makes sense
