### ISSUE TITLE
[UX Review] Client scope/mappers/creation-Add predefined mappers

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-admin-ui#654]
Hi @edewit, this part focuses on adding predefined mappers. Please check the following pictures and comments.

<img width="879" alt="Screen Shot 2021-05-31 at 2 38 27 PM" src="https://user-images.githubusercontent.com/53931519/120165140-d81c9200-c22d-11eb-93ad-f3e57cdff335.png">

1. The header should be "Add predefined mappers". 
2. The description should be fixed under the title.
3. We can add a search bar to help users search the target mappers. 
4. We can add a checkbox that allows users to select all predefined mappers. If possible, we can divide all mappers into pages.

> <img width="798" alt="Screen Shot 2021-05-31 at 4 38 38 PM" src="https://user-images.githubusercontent.com/53931519/120166154-e28b5b80-c22e-11eb-9d5f-e96f075ea7ab.png">

5. All mappers are sorted alphabetically.

**Comment by ssilvert** [comment]
Looks fixed.  Closing.
