### ISSUE TITLE
[UX Review] Client scope/mappers/creation-Configure new mapper

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-admin-ui#665]
Hi @edewit, in this part, I will update some issues about "Add mapper by configuration". Please check the following comments.

**[Creation modal]**

> <img width="878" alt="Screen Shot 2021-06-03 at 1 16 41 PM" src="https://user-images.githubusercontent.com/53931519/120591408-ae9e7900-c46e-11eb-8790-7d32003e634a.png">

1. The description should be fixed under the title. Moreover, the distance between the description and the table should be 24 px.
2. The table has a heading that includes "Mapper type" and "Description". 
<img width="792" alt="Screen Shot 2021-06-03 at 1 26 52 PM" src="https://user-images.githubusercontent.com/53931519/120591851-6df32f80-c46f-11eb-8938-6be33f6eaac8.png">

3. All options are sorted alphabetically.

**Comment by xianli123** [comment]
**[Creation page]**

> <img width="1147" alt="Screen Shot 2021-06-03 at 1 42 42 PM" src="https://user-images.githubusercontent.com/53931519/120593670-67b28280-c472-11eb-975f-34fb0432985b.png">

1. As for the breadcrumb, we can show "Client scopes > (current client scope name) > Add mapper". Client scope and the current client scope name are hyper links.
2. We don't need to display the protocol here. And the header should be "Add mapper" instead of the mapper type.
3. Here's a description. Maybe we need Andy's help.
4. We can display the mapper type in the form firstly and it's not editable.
5. These three options should be selected by default.
6. The "Cancel" doesn't work.

**Comment by ssilvert** [comment]
@xianli123 Can you put the creation page stuff in a separate issue and then remove the comment about it?

**Comment by xianli123** [comment]
@ssilvert I created a new issue to record the requirements of creation page, please check the link here. https://github.com/keycloak/keycloak-admin-ui/issues/968

**Comment by ssilvert** [comment]
Looks fixed to me.
