### ISSUE TITLE
[UX Review] Client - Service account roles

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-admin-ui#667]
hi @edewit, in this issue, I will leave some comments about the "Service account roles". Please check the comments below.

**[Table]**

> <img width="1151" alt="Screen Shot 2021-06-04 at 2 07 00 PM" src="https://user-images.githubusercontent.com/53931519/120754471-4d92a600-c53f-11eb-88a7-f5cccf779c14.png">
1. There is a question mark. After clicking the question mark, there will be a piece of help info: "Disabled clients cannot initiate a login or have obtained access tokens."   
2. Please change "Service account" to "Service account roles".    
3. There should be a checkbox in front of each role and the checkboxes of Inherited roles are disabled.    
4. Each direct role is followed by a kebab. Click the kebab icon and then click the "Unassign" to unassign the role. Please note that if the roles are inherited roles, the kebab should be disabled.

**Comment by xianli123** [comment]
**[Assign modal]**

> <img width="1145" alt="Screen Shot 2021-06-04 at 2 34 49 PM" src="https://user-images.githubusercontent.com/53931519/120757470-2ccc4f80-c543-11eb-8596-01d466d0c728.png">

1. Put the filter bar and the search bar together. If possible, we can fix the top filter and search bar. 
2. We can put a check box here. 

Please refer to the screenshot below.

<img width="656" alt="Screen Shot 2021-06-04 at 2 44 28 PM" src="https://user-images.githubusercontent.com/53931519/120757705-77e66280-c543-11eb-8613-28da096539c8.png">

**Comment by edewit** [comment]
> There should be a checkbox in front of each role and the checkboxes of Inherited roles are disabled.
These only appear when you check "Hide inherited roles" as the inherited roles can not be removed.

**Comment by xianli123** [comment]
I think we should show the check box even though "Hide inherited role" is not marked. We can use the disabled checkbox to indicate that this role is an inherited role as shown in the screenshot below. What do you think?

> <img width="517" alt="Screen Shot 2021-06-10 at 5 17 36 PM" src="https://user-images.githubusercontent.com/53931519/121499876-5e945900-ca10-11eb-8799-2d115a4e1335.png">
