### ISSUE TITLE
[UX Review] Groups - Attributes

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-admin-ui#679]
Hi @edewit, this issue is about the Attributes tab in the Groups details page, please check the comments below.

> <img width="883" alt="Screen Shot 2021-06-07 at 2 34 54 PM" src="https://user-images.githubusercontent.com/53931519/120987041-c861f800-c7af-11eb-8de6-bd4eda374221.png">

1. The header should display the group's name.
2. The vertical distance between the form and the button should be 40px.
3. If users didn't fill in the first Key and Value, users can't save the changes.

**Comment by ssilvert** [comment]
@xianli123 Can you take another look at this one?  I think it might be all fixed.  If so, please close it.

I do see something else that's weird.  Every time you save, it adds a row.  But that can be addressed in a new issue later.  It doesn't actually cause problems.  It's just cosmetic.

**Comment by xianli123** [comment]
@ssilvert I've checked the new implementation. I found point ① and ② have been resolved, but the ③ is not fixed yet. If users don't fill in the Key and Value, the Save button should be disabled. If we fix the ③, the problem that you mentioned inn the last comment will be resolved at the same time.
