### ISSUE TITLE
Realm role CRUD test broken in CI

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-admin-ui#713]
The "Realm role CRUD test" in realm_roles_test_spec.ts fails on GitHub PR's.  However, it does work locally.

This problem appears to have been introduced with PR #693.  In the interest of time, we decided to go ahead and merge.

The test was commented out by PR #712.

This needs a closer look so we can have a working Realm role CRUD test in CI.

**Comment by jonkoops** [comment]
Fixed in https://github.com/keycloak/keycloak-admin-ui/pull/897
