### ISSUE TITLE
Reset Actions modification

### ISSUE THREAD

**Issue by ilyuxa-sw97** [keycloak/keycloak-admin-ui#719]
In the admin panel in the  users tab there is a block for resetting the password and other actions.   
<img width="917" alt="Снимок экрана 2021-06-21 в 09 05 36" src="https://user-images.githubusercontent.com/36299101/122714528-18d95b00-d270-11eb-9ca2-6bb9254b95f2.png">

when using this panel, when generating a link, it will use the address in the browser. This is not very convenient because when using intermediate hosts and ssh tunnels, the address will look like a https://localhost:9000.
When in fact he has a different dns in front of the firewall.

**Comment by edewit** [comment]
This is the repository of the new admin console, we don't have this functionality yet. I think this is an issue for Keycloak can you fill this issue in [jira](https://issues.redhat.com/browse/KEYCLOAK)?

**Comment by jonkoops** [comment]
This specific repository is for the new Keycloak Admin UI, which is not yet in production. The issue mentioned here is therefore not relevant for this specific project. Please report this issue to the Keycloak team through the official channels of as stated on our [community page](https://www.keycloak.org/community).
