### ISSUE TITLE
Lay out Groups section

### ISSUE THREAD

**Issue by jenny-s51** [keycloak/keycloak-admin-ui#82]
https://marvelapp.com/prototype/228971ig/screen/72210509

**Comment by ImaCrea** [comment]
Hello @jenny-s51 I took a look at your mockup and it looks promising! Very close to what we'd need here at IndieHosters.
I was wondering how is this project going and if there's any chance to see this new group section working soon :)

**Comment by jenny-s51** [comment]
Hi @ImaCrea, thank you for reaching out - we're currently working on the implementation of the groups section and plan to have it up for community review soon. 

cc: @edewit

**Comment by ImaCrea** [comment]
This is great news @jenny-s51 thanks. Can't wait to test it out :)
