### ISSUE TITLE
All buttons have corrupted names with labels like {{

### ISSUE THREAD

**Issue by dgroup** [keycloak/keycloak-admin-ui#873]
**Test case:**
1. Install `docker run --name keycloak -e DB_VENDOR=H2 -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin -p 8180:8080 quay.io/keycloak/keycloak:14.0.0`
2. Login to http://localhost:8180/auth/admin/master/console/#/realms/master/users
3. Press tab `Users`

**Expected results:**
List of available users if any.

**Actual results:**
![image](https://user-images.githubusercontent.com/1651114/126041826-56d919ee-b869-4c8a-9679-96bd86e66d6d.png)

**Browser version**
![image](https://user-images.githubusercontent.com/1651114/126042648-1aa6c23d-6764-433a-8239-4143cb3572b3.png)
![image](https://user-images.githubusercontent.com/1651114/126042658-69cffb41-d2ce-4698-991d-cd7b19f654e4.png)

**Comment by jonkoops** [comment]
Could you try running the application from a more recent version of these browsers? Version 72.0.2 of Firefox is from January, 2020, and Vivaldi 2.4 is from April, 2019. Neither of the browsers fall in our browser support target, so any reported bugs for them will unfortunately not be resolved.

**Comment by jonkoops** [comment]
On a second look, this is not the new Keycloak Admin UI, rather this is the old one that comes with Keycloak out of the box. If you are experiencing issues with that, please report this issue on the [main repository](https://github.com/keycloak/keycloak/).
