### ISSUE TITLE
[Security] Javascript Injection and Execution

### ISSUE THREAD

**Issue by anshulpatel25** [keycloak/keycloak-admin-ui#915]
**Bug**

If the permission name has `<script>` tag, it gets executed when we try to delete resource associated with it.

**Steps to Reproduce**

- Create a resource under Authorization in the client.
- Create a permission which has `<script>` tag in it. For e.g. `permission:<script>alert(1)</script>:admin` and associate the above created resource with the permission.
- Now, try to delete the resource, it will pop the alert like the below screenshot
![image](https://user-images.githubusercontent.com/1756518/127088411-b5d1e9d2-4462-4b47-ad85-79db8576e2c6.png)

**Comment by jonkoops** [comment]
Hi @anshulpatel25, I have spoken with the team and we believe this issue has been resolved in `master`. If not, please report this issue to the Keycloak team through the official channels of as stated on our [community page](https://www.keycloak.org/community).

This specific repository is for the new Keycloak Admin UI, which is not yet in production. The issue mentioned here is therefore not relevant for this specific project.
