### ISSUE TITLE
[UX Review] The Save button styles are not correct in the Advanced tab

### ISSUE THREAD

**Issue by yih-wang** [keycloak/keycloak-admin-ui#959]
Location: Client > Advanced

The Save button styles of the last four cards should be Secondary (blue) instead of Tertiary (black).

![image](https://user-images.githubusercontent.com/23331885/128708306-ebe4e47f-d207-467f-b5e0-ef8b498f8123.png)

**Comment by edewit** [comment]
In my defense the where designed that way: https://marvelapp.com/prototype/9a93gef/screen/75845550

**Comment by yih-wang** [comment]
> In my defense the where designed that way: https://marvelapp.com/prototype/9a93gef/screen/75845550

The design also shows the secondary style - 
![image](https://user-images.githubusercontent.com/23331885/129533555-5ee6e3f0-e29b-4259-99a4-e00d0ea29823.png)
