### ISSUE TITLE
[UX Review] Client scope/mappers/creation page

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-admin-ui#968]
Hi @ssilvert @edewit ，I separate the mapper creation page as a new issue here, please check it.

![image](https://user-images.githubusercontent.com/53931519/128817885-bf563867-e8f4-4b69-827e-99ca480118bc.png)

1. As for the breadcrumb, we can show "Client scopes > (current client scope name) > Add mapper". Client scope and the current client scope name are hyperlinks.
2. We don't need to display the protocol here. And the header should be "Add mapper" instead of the mapper type.
3. Here's a description. Maybe we need Andy's help.
4. We can display the mapper type in the form firstly and it's not editable.
5. These three options should be selected by default.
6. The "Cancel" doesn't work.

**Comment by ssilvert** [comment]
@edewit I this all fixed?  If so, go ahead and close.
