### ISSUE TITLE
Realm selector display problems with > 5 realms

### ISSUE THREAD

**Issue by srambach** [keycloak/keycloak-admin-ui#97]
@edewit reports there is a display issue for the realm selector when there are more than 5 realms.

**Comment by edewit** [comment]
The problem is with the current selected realm (indicted by a little ✓) the icon is not lining up like on the version with less then 5 items.
![image](https://user-images.githubusercontent.com/51133/93596887-6875b800-f9ba-11ea-8a26-0193c2e1720c.png)

**Comment by edewit** [comment]
plus there must be more whitespace on the "Create Realm" button
