### ISSUE TITLE
Log into test realm fails

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-admin-ui#981]
If I try to login to admin console as a user in "Test" realm, the app fails to load.

Running as keycloak theme, I get 404 error on http://localhost:8180/auth/realms/a3b79f3e-d87b-480c-8e81-aab5ff4b65e4/protocol/openid-connect/3p-cookies/step1.html

Running in dev mode, (http://localhost:8080/?realm=test) it also does not work.

**Comment by ssilvert** [comment]
@edewit Please fix this ASAP.  We can't release to Keycloak master if this doesn't work.

**Comment by edewit** [comment]
@ssilvert what rights did you give this user?

**Comment by ssilvert** [comment]
This issue is invalid.  `loginRealm` specified in index.ftl is currently hard-coded.  This won't be fixed until I submit a new PR to Keycloak server.  So for now, to test this we have to change the hard-coded value of `loginRealm`.
